<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use stdClass;

class _inm_ubicaciones extends _modelo_base_paquete {

    /**
     * Inserta un registro de tipo ubicaciones
     * @param array $keys_integra_ds Keys para integracion de descripcion select
     * @return array|stdClass
     * @version 2.93.0
     */
    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $registro = $this->registro;

        $registro = $this->init_row(key_entidad_base_id: $this->key_id, key_entidad_id: $this->key_entidad_id,
            registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar descripcion',data:  $registro);
        }


        $this->registro = $registro;

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar ubicacion',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }

    /**
     * Se tiene que determinar en objeto que hereda
     * @param string $key_entidad_base_id
     * @param string $key_entidad_id
     * @param array $registro Registro en proceso
     * @return array
     * @version 1.45.0
     */
    public function init_row(string $key_entidad_base_id, string $key_entidad_id, array $registro): array
    {
        return $registro;
    }

    final public function integra_inm_documentos(controlador_inm_ubicacion $controler){
        $inm_prospecto = (new inm_prospecto_ubicacion(link: $controler->link))->registro(registro_id: $controler->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener inm_prospecto',data:  $inm_prospecto);
        }

        $filtro['inm_conf_docs_prospecto_ubicacion.es_foto'] = 'inactivo';
        $inm_conf_docs_prospecto = (new inm_conf_docs_ubicacion(link: $controler->link))->filtro_and(
            columnas: ['doc_tipo_documento_id'],
            filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener inm_conf_docs_prospecto',data:  $inm_conf_docs_prospecto);
        }

        $doc_ids = array_map(function($registro) {
            return $registro['doc_tipo_documento_id'];
        }, $inm_conf_docs_prospecto->registros);

        if (count($doc_ids) <= 0) {
            return array();
        }

        $inm_docs_prospecto = (new inm_doc_ubicacion(link: $controler->link))->inm_docs_prospecto_ubicacion(
            inm_prospecto_ubicacion: $controler->registro_id, tipos_documentos: $doc_ids);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener inm_docs_prospecto',data:  $inm_docs_prospecto);
        }

        $inm_docs_prospecto = $this->inm_conf_docs_prospecto(controler: $controler,inm_docs_prospecto:  $inm_docs_prospecto,
            tipos_documentos: $doc_ids);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar buttons',data:  $inm_docs_prospecto);
        }

        return $inm_docs_prospecto;
    }


    /**
     * Valida los elementos base de una inicializacion de ubicacion
     * @param array $registro Registro en proceso
     * @return array|true
     * @version 2.95.0
     */
    final protected function valida_row(array $registro): bool|array
    {
        $keys = array('dp_colonia_postal_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida $registro',data:  $valida);
        }

        $keys = array('numero_exterior');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida $registro',data:  $valida);
        }
        return true;
    }

}