<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_poder extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_poder';
        $columnas = array($tabla=>false,'inm_notaria'=>$tabla, 'inm_ubicacion'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Poder';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' '.$this->registro['inm_notaria_id'];
            $descripcion .= ' '.$this->registro['numero_escritura_poder'];
            $this->registro['descripcion'] = $descripcion;
        }

        if(!isset($this->registro['codigo'])){
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' '.$this->registro['inm_notaria_id'];
            $descripcion .= ' '.$this->registro['numero_escritura_poder'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }

}