<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_notificacion_periodo extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_notificacion_periodo';
        $columnas = array($tabla=>false, 'not_mensaje'=>$tabla, 'inm_periodo_asistencia'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Notificacion Periodo';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        if (!isset($this->registro['descripcion'])) {
            $descripcion = 'Periodo ID: '. $this->registro['inm_periodo_asistencia_id'];
            $descripcion .= ' - Mensaje ID: ' .  $this->registro['not_mensaje_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['descripcion_select'])) {
            $descripcion_select = 'Periodo ID: '. $this->registro['inm_periodo_asistencia_id'];
            $descripcion_select .= ' - Mensaje ID: ' .  $this->registro['not_mensaje_id'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($this->registro['codigo'])) {
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }
}