<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use gamboamartin\gastos\models\gt_proveedor;
use PDO;
use stdClass;


class inm_factura_compra extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_factura_compra';
        $columnas = array($tabla=>false,'gt_proveedor'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Factura Compra';
    }


    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $r_proveedor = (new gt_proveedor(link: $this->link))->registro(registro_id: $this->registro['gt_proveedor_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_proveedor);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_proveedor['gt_proveedor_razon_social'];
            $descripcion .= ' ' . $this->registro['fecha'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $r_proveedor['gt_proveedor_razon_social'];
            $descripcion .= ' ' . $this->registro['fecha'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_proveedor = (new gt_proveedor(link: $this->link))->registro(registro_id: $registro['gt_proveedor_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_proveedor);
        }

        if(!isset($registro['status'])){
            if (!isset($registro['descripcion'])) {
                $descripcion = $r_proveedor['gt_proveedor_razon_social'];
                $descripcion .= ' ' . $registro['fecha'];
                $registro['descripcion'] = $descripcion;
            }

            if (!isset($registro['codigo'])) {
                $descripcion = $r_proveedor['gt_proveedor_razon_social'];
                $descripcion .= ' ' . $registro['fecha'] . rand();
                $registro['codigo'] = $descripcion;
            }
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}