<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_efectivo extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_efectivo';
        $columnas = array($tabla=>false);

        $columnas_extra= array();
        $renombres= array();

        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'efectivo';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['nombre_beneficiario'];
            $descripcion .= ' '.$this->registro['monto'];
            $this->registro['descripcion'] = $descripcion;
        }

        if(!isset($this->registro['codigo'])){
            $descripcion = $this->registro['nombre_beneficiario'];
            $descripcion .= ' '.$this->registro['monto'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }

    final public function data_pdf(int $registro_id): array|stdClass
    {
        if($registro_id<=0){
            return $this->error->error(mensaje: 'Error al registro_id debe ser mayor a 0',
                data: $registro_id);
        }

        $filtro['inm_efectivo.id'] = $registro_id;
        $inm_efectivo = (new inm_rel_efectivo_ubicacion(link: $this->link))->filtro_and(filtro: $filtro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener efectivo', data: $inm_efectivo);
        }

        $data = new stdClass();
        $data->inm_efectivo = $inm_efectivo->registros[0];
        $data->nombre_archivo = 'solicitud_gasto - '.$inm_efectivo->registros[0]['inm_cheque_nombre_beneficiario']
            .'.pdf';

        return $data;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $modelo_inm_rel = new inm_rel_costo_efectivo(link: $this->link);
        $filtro['inm_efectivo.id'] = $id;
        $r_rel = $modelo_inm_rel->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener relacion',data:  $r_rel);
        }

        if($r_rel->n_registros > 0) {
            $r_elimina = $modelo_inm_rel->elimina_bd(id: $r_rel->registros[0]['inm_rel_costo_efectivo_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener relacion', data: $r_elimina);
            }
        }

        $r_elimina_bd = parent::elimina_bd(id:  $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar descripcion',data:  $r_elimina_bd);
        }

        return $r_elimina_bd;
    }
    
    public function modifica_bd(array $registro, int $id, bool $reactiva = false, array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id,reactiva:  $reactiva,
            keys_integra_ds:  $keys_integra_ds);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar descripcion',data:  $r_modifica_bd);
        }

        $filtro['inm_efectivo.id'] = $id;
        $r_rel_costo_efectivo = (new inm_rel_costo_efectivo(link: $this->link))->filtro_and(filtro:$filtro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_rel_costo_efectivo);
        }

        if($r_rel_costo_efectivo->n_registros > 0){
            $registro_che = array();
            $registro_che['monto'] = $registro['monto'];
            $registro_che['referencia'] = $registro['nombre_beneficiario'];
            $r_efectivo = (new inm_costo(link:$this->link))->modifica_bd(registro: $registro_che,
                id: $r_rel_costo_efectivo->registros[0]['inm_costo_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_efectivo);
            }
        }else{
            $filtro['inm_efectivo.id'] = $id;
            $r_efectivo_fil = (new inm_rel_efectivo_ubicacion(link: $this->link))->filtro_and(filtro:$filtro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_efectivo_fil);
            }

            $registro_che = array();
            $registro_che['inm_ubicacion_id'] = $r_efectivo_fil->registros[0]['inm_ubicacion_id'];
            $registro_che['monto'] = $registro['monto'];
            $registro_che['fecha'] = date('Y-m-d');
            $registro_che['referencia'] = $registro['nombre_beneficiario'];
            $registro_che['inm_concepto_id'] = 19;

            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(registro: $registro_che);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }

            $registro = array();
            $registro['inm_costo_id'] = $r_inm_costo->registro_id;
            $registro['inm_efectivo_id'] = $id;
            $r_rel_costo_efectivo = (new inm_rel_costo_efectivo(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_rel_costo_efectivo);
            }
        }

        return $r_modifica_bd;
    }

}