<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_costo extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_costo';
        $columnas = array($tabla=>false,'inm_concepto'=>$tabla,'inm_ubicacion'=>$tabla,
            'inm_tipo_concepto'=>'inm_concepto');

        $campos_obligatorios = array('inm_concepto_id','inm_ubicacion_id','monto','fecha','referencia');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('inm_ubicacion_id','inm_concepto_id','monto','fecha','referencia');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Costo Ubicaciones';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('inm_ubicacion_id','inm_concepto_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $keys = array('monto');
        $valida = $this->validacion->valida_double_mayores_igual_0(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $keys = array('fecha');
        $valida = $this->validacion->fechas_in_array(data: $this->registro,keys:  $keys);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $inm_ubicacion = (new inm_ubicacion(link: $this->link))->registro(
            registro_id: $this->registro['inm_ubicacion_id'],retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener ubicacion',data:  $inm_ubicacion);
        }


        $registro = $this->integra_codigo(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar codigo',data:  $registro);
        }


        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        $regenera = (new inm_ubicacion(link: $this->link))->regenera_datas(
            inm_ubicacion_id: $r_alta_bd->registro_puro->inm_ubicacion_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al regenerar costo', data: $regenera);
        }


        return $r_alta_bd;
    }

    /**
     * Genera un codigo basado en datos
     * @param array $registro registro en proceso
     * @return string|array
     */
    private function codigo(array $registro): string|array
    {
        $keys = array('referencia','fecha','inm_ubicacion_id','monto','inm_concepto_id');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro', data: $valida);
        }

        $keys = array('fecha');
        $valida = $this->validacion->fechas_in_array(data: $registro, keys: $keys);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro', data: $valida);
        }

        $keys = array('inm_ubicacion_id','inm_concepto_id');
        $valida = $this->validacion->valida_ids(keys: $keys, registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro', data: $valida);
        }

        $monto = $registro['monto'];
        $monto = str_replace('$','', $monto);
        $monto = str_replace(' ','', $monto);
        $monto = str_replace(' ','', $monto);
        $monto = str_replace(' ','', $monto);
        $monto = str_replace(' ','', $monto);
        $monto = str_replace(' ','', $monto);
        $monto = str_replace(',','', $monto);
        $monto = str_replace("'",'', $monto);

        $monto = trim($monto);
        if(!is_numeric($monto)){
            return $this->error->error(mensaje: 'Error monto no es un numero valido', data: $monto);
        }

        $registro['monto'] = $monto;

        if(!isset($registro['descripcion'])){
            $registro['descripcion'] = $registro['referencia'].' '.$registro['fecha'];
        }
        $codigo = $registro['descripcion'];
        $codigo .= $registro['inm_ubicacion_id'];
        $codigo .= $registro['inm_concepto_id'];
        $codigo .= $registro['referencia'];
        $codigo .= $registro['fecha'];
        $codigo .= $registro['monto'];
        return $codigo;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $r_elimina_bd = parent::elimina_bd(id: $id); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar opinion', data: $r_elimina_bd);
        }

        $regenera = (new inm_ubicacion(link: $this->link))->regenera_datas(
            inm_ubicacion_id: $r_elimina_bd->registro_puro->inm_ubicacion_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al regenerar opinion de valor', data: $regenera);
        }


        return $r_elimina_bd;
    }

    private function integra_codigo(array $registro){
        if(!isset($registro['codigo'])){
            $codigo = $this->codigo(registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al generar codigo',data:  $codigo);
            }
            $registro['codigo'] = $codigo;
        }
        return $registro;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        $regenera = (new inm_ubicacion(link: $this->link))->regenera_datas(
            inm_ubicacion_id: $r_modifica_bd->registro_actualizado->inm_ubicacion_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al regenerar opinion de valor', data: $regenera);
        }

        $registro_upd = $this->integra_codigo(registro: $r_modifica_bd->registro_puro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar codigo',data:  $registro);
        }
        $upd_code = parent::modifica_bd(registro: $registro_upd,id:  $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al actualizar codigo',data:  $upd_code);
        }


        return $r_modifica_bd;
    }

}