<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_rel_cheque_ubicacion extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_cheque_ubicacion';
        $columnas = array($tabla=>false,'inm_cheque'=>$tabla,'inm_ubicacion'=>$tabla,'inm_tipo_cheque'=>'inm_cheque',
            'bn_cuenta'=>'inm_cheque', 'dp_colonia_postal'=>'inm_ubicacion', 'dp_cp'=>'dp_colonia_postal',
            'dp_colonia'=>'dp_colonia_postal', 'dp_municipio'=>'dp_cp', 'dp_estado'=>'dp_municipio',
            'dp_pais'=>'dp_estado');

        $campos_obligatorios = array();

        $columnas_extra= array();
        $sql = "(CONCAT_WS(' ', inm_ubicacion.calle, inm_ubicacion.numero_exterior, 
        inm_ubicacion.numero_interior, dp_colonia.descripcion, dp_municipio.descripcion))";

        $columnas_extra['inm_ubicacion_ubicacion'] = $sql;

        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion Cheque';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['inm_cheque_id'])) {
            $registro_cheque = array();

            //$registro_cheque['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro_cheque['monto'] = $this->registro['monto'];
            $registro_cheque['nombre_beneficiario'] = $this->registro['nombre_beneficiario'];
            $registro_cheque['inm_tipo_cheque_id'] = $this->registro['inm_tipo_cheque_id'];
            $registro_cheque['numero_cheque'] = '';

            if (isset($this->registro['numero_cheque'])) {
                $registro_cheque['numero_cheque'] = $this->registro['numero_cheque'];
            }

            $r_inm_cheque = (new inm_cheque(link: $this->link))->alta_registro(registro: $registro_cheque);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_cheque);
            }

            $this->registro['inm_cheque_id'] = $r_inm_cheque->registro_id;

            $registro = array();
            $registro['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro['monto'] = $this->registro['monto'];
            $registro['fecha'] = date('Y-m-d');
            $registro['referencia'] = $this->registro['nombre_beneficiario'];

            if(trim($this->registro['inm_tipo_cheque_id']) === "1"){
                $registro['inm_concepto_id'] = 19;
            }else if(trim($this->registro['inm_tipo_cheque_id']) === "2"){
                $registro['inm_concepto_id'] = 36;
            }else if(trim($this->registro['inm_tipo_cheque_id']) === "3"){
                $registro['inm_concepto_id'] = 19;
            }else{
                $registro['inm_concepto_id'] = 19;
            }

            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }

            $registro = array();
            $registro['inm_costo_id'] = $r_inm_costo->registro_id;
            $registro['inm_cheque_id'] = $r_inm_cheque->registro_id;
            $r_rel_costo_cheque = (new inm_rel_costo_cheque(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_rel_costo_cheque);
            }

            unset($this->registro['monto'], $this->registro['nombre_beneficiario'],
                $this->registro['inm_tipo_cheque_id'], $this->registro['numero_cheque']);
        }


        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' ' . $this->registro['inm_cheque_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' ' . $this->registro['inm_cheque_id'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $filtro = array();
        $filtro['inm_rel_cheque_ubicacion.id'] = $id;
        $r_rel = $this->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener relacion',data:  $r_rel);
        }

        if($r_rel->n_registros > 0) {
            $modelo_inm_doc = new inm_rel_doc_cheque_ubicacion(link: $this->link);

            $filtro = array();
            $filtro['inm_cheque.id'] = $r_rel->registros[0]['inm_cheque_id'];
            $r_doc = $modelo_inm_doc->filtro_and(filtro: $filtro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener relacion documento', data: $r_doc);
            }

            if ($r_doc->n_registros > 0) {
                return $this->error->error(mensaje: 'Error al existe un documento de poliza cheque', data: $r_doc);
            }
        }

        $r_elimina_bd = parent::elimina_bd(id:  $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar descripcion',data:  $r_elimina_bd);
        }
        
        if($r_rel->n_registros > 0) {
            $r_elimina = (new inm_cheque(link: $this->link))->elimina_bd(id: $r_rel->registros[0]['inm_cheque_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener relacion', data: $r_elimina);
            }
        }

        return $r_elimina_bd;
    }

}