<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use gamboamartin\gastos\models\gt_proveedor;
use PDO;


class inm_almacen extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_almacen';
        $columnas = array($tabla=>false, 'inm_tipo_almacen'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra = array();
        $renombres = array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Almacen';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|\stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_tipo_almacen_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if(!isset($this->registro['codigo'])){
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }

}