<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_rel_agente_comprador extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_prospecto_cliente';
        $columnas = array($tabla=>false,'com_agente'=>$tabla, 'inm_comprador'=>$tabla);

        $campos_obligatorios = array('com_agente_id','inm_comprador_id');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('com_agente_id','inm_comprador_id');


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion cliente prospecto';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $valida = $this->valida_alta_relacion(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->descripcion(registro: $this->registro );
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener descripcion',data:  $descripcion);
            }

            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar', data: $r_alta_bd);
        }

        return $r_alta_bd;

    }

    private function descripcion(array $registro): string|array
    {

        $valida = $this->valida_alta_relacion(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }

        $descripcion = $registro['inm_comprador_id'];
        $descripcion .= ' '.$registro['com_agente_id'];
        return $descripcion;
    }

    private function valida_alta_relacion(array $registro){

        $keys = array('inm_comprador_id','com_agente_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }
        return true;
    }


}