<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_referencia_prospecto extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_referencia_prospecto';
        $columnas = array($tabla=>false,'inm_prospecto'=>$tabla,'dp_calle_pertenece'=>$tabla,
            'inm_parentesco'=>$tabla);

        $campos_obligatorios = array('inm_prospecto_id','dp_calle_pertenece_id','inm_parentesco_id','apellido_paterno',
            'nombre','lada','numero','celular','numero_dom');

        $columnas_extra= array();

        $renombres = array();

        $atributos_criticos = array('inm_prospecto_id','dp_calle_pertenece_id','inm_parentesco_id','apellido_paterno',
            'apellido_materno','nombre','lada','numero','celular','numero_dom');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Referencias';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $keys = array('inm_prospecto_id','dp_calle_pertenece_id','inm_parentesco_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->descripcion(registro: $this->registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al integrar descripcion',data:  $descripcion);
            }

            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar', data: $r_alta_bd);
        }


        return $r_alta_bd;

    }

    private function descripcion(array $registro): string
    {
        $descripcion = $registro['inm_prospecto_id'];
        $descripcion .= ' '.$registro['dp_calle_pertenece_id'];
        $descripcion .= ' '.$registro['inm_parentesco_id'];
        $descripcion .= ' '.$registro['nombre'];
        $descripcion .= ' '.$registro['apellido_paterno'];

        return $descripcion;
    }

}