<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\cat_sat\models\cat_sat_cve_prod;
use gamboamartin\cat_sat\models\cat_sat_unidad;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_producto extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_producto';
        $columnas = array($tabla=>false,'cat_sat_unidad'=>$tabla,'cat_sat_cve_prod'=>$tabla,'inm_concepto'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Producto';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $r_cat_sat_unidad = (new cat_sat_unidad(link: $this->link))->registro(
            registro_id: $this->registro['cat_sat_unidad_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener unidad', data: $r_cat_sat_unidad);
        }

        $filtro['cat_sat_cve_prod.codigo'] = $this->registro['cat_sat_cve_prod_codigo'];
        $r_cat_sat_cve_prod = (new cat_sat_cve_prod(link: $this->link))->filtro_and(filtro: $filtro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener clave producto sat', data: $r_cat_sat_cve_prod);
        }

        if ($r_cat_sat_cve_prod->n_registros <= 0) {
            return $this->error->error(mensaje: 'Error no existe la clave producto sat', data: $r_cat_sat_cve_prod);
        }

        $this->registro['cat_sat_cve_prod_id'] = $r_cat_sat_cve_prod->registros[0]['cat_sat_cve_prod_id'];

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_cat_sat_cve_prod->registros[0]['cat_sat_cve_prod_descricion'];
            $descripcion .= ' '. $r_cat_sat_unidad['cat_sat_unidad_descripcion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        if (!isset($this->registro['descripcion_select'])) {
            $descripcion_select = $this->registro['descripcion'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($registro['status']) && !isset($registro['enviado'])){
            $r_cat_sat_unidad = (new cat_sat_unidad(link: $this->link))->registro(
                registro_id: $registro['cat_sat_unidad_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_cat_sat_unidad);
            }

            $filtro['cat_sat_cve_prod.codigo'] = $registro['cat_sat_cve_prod_codigo'];
            $r_cat_sat_cve_prod = (new cat_sat_cve_prod(link: $this->link))->filtro_and(filtro: $filtro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_cat_sat_cve_prod);
            }

            if ($r_cat_sat_cve_prod->n_registros <= 0) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_cat_sat_cve_prod);
            }

            $registro['cat_sat_cve_prod_id'] = $r_cat_sat_cve_prod->registros[0]['cat_sat_cve_prod_id'];

            if (!isset($registro['descripcion'])) {
                $descripcion = $r_cat_sat_cve_prod->registros[0]['cat_sat_cve_prod_descricion'];
                $descripcion .= ' '. $r_cat_sat_unidad['cat_sat_unidad_descripcion'];
                $registro['descripcion'] = $descripcion;
            }

            if (!isset($registro['codigo'])) {
                $descripcion = $registro['descripcion'] . rand();
                $registro['codigo'] = $descripcion;
            }

            if (!isset($registro['descripcion_select'])) {
                $descripcion_select = $registro['descripcion'];
                $registro['descripcion_select'] = $descripcion_select;
            }
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}