<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;


class inm_checada extends _modelo_parent{
    public $hora_limite = '09:15:00';
    public function __construct(PDO $link)
    {
        $tabla = 'inm_checada';
        $columnas = array($tabla=>false,'inm_empleado'=>$tabla,'inm_status_asistencia'=>$tabla,
            'inm_periodo_asistencia'=>$tabla,'inm_tipo_checada'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Status Comprador';
    }


    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|\stdClass
    {
        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['inm_empleado_id'];
            $descripcion .= ' ' . $this->registro['fecha'];
            $descripcion .= ' ' . $this->registro['hora'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['inm_empleado_id'];
            $descripcion .= ' ' . $this->registro['fecha'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        if (!isset($this->registro['inm_tipo_checada_id'])) {
            $this->registro['inm_tipo_checada_id'] = 1;
        }

        if (!isset($this->registro['inm_status_asistencia_id'])) {
            if($this->registro['inm_tipo_checada_id'] === 1){
                $filtro_rango[$this->registro['hora']]['valor1'] = 'inm_politica_asistencia.hora_inicio';
                $filtro_rango[$this->registro['hora']]['valor2'] = 'inm_politica_asistencia.hora_fin';
                $filtro_rango[$this->registro['hora']]['valor_campo'] = true;

                $order = array('inm_politica_asistencia.hora_inicio'=>'DESC');

                $r_politica_asistencia = (new inm_politica_asistencia(link:$this->link))->filtro_and(
                    filtro_rango: $filtro_rango, limit: 1, order: $order);
                if (errores::$error) {
                    return $this->error->error(mensaje: 'Error al obtener politicas', data: $r_politica_asistencia);
                }

                if($r_politica_asistencia->n_registros <= 0){
                    return $this->error->error(mensaje: 'Error no existe politica de asistencia',
                        data: $r_politica_asistencia);
                }

                $this->registro['inm_status_asistencia_id'] =
                    $r_politica_asistencia->registros[0]['inm_status_asistencia_id'];
            }else{
                $this->registro['inm_status_asistencia_id'] = 1;
            }
        }

        if (!isset($this->registro['inm_periodo_asistencia_id'])) {
            $filtro_rango[$this->registro['fecha']]['valor1'] = 'inm_periodo_asistencia.fecha_inicio';
            $filtro_rango[$this->registro['fecha']]['valor2'] = 'inm_periodo_asistencia.fecha_fin';
            $filtro_rango[$this->registro['fecha']]['valor_campo'] = true;

            $order = array('inm_periodo_asistencia.fecha_inicio'=>'DESC');

            $r_periodo_asistencia = (new inm_periodo_asistencia(link:$this->link))->filtro_and(
                filtro_rango: $filtro_rango, limit: 1, order: $order);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener periodos', data: $r_periodo_asistencia);
            }

            if($r_periodo_asistencia->n_registros <= 0){
                return $this->error->error(mensaje: 'Error no existe periodo de asistencia',
                    data: $r_periodo_asistencia);
            }

            $this->registro['inm_periodo_asistencia_id'] =
                $r_periodo_asistencia->registros[0]['inm_periodo_asistencia_id'];
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar checada', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }
}