<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_rel_doc_transferencia_ubicacion extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_doc_transferencia';
        $columnas = array($tabla=>false, 'inm_transferencia' => $tabla, 'inm_doc_ubicacion' => $tabla,
            'doc_documento'=>'inm_doc_ubicacion', 'doc_tipo_documento'=>'doc_documento');

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion Documento transferencia';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $valida = $this->valida_alta_relacion(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->descripcion(registro: $this->registro );
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener descripcion',data:  $descripcion);
            }

            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar', data: $r_alta_bd);
        }

        return $r_alta_bd;

    }

    private function descripcion(array $registro): string|array
    {

        $valida = $this->valida_alta_relacion(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }

        $descripcion = $registro['inm_transferencia_id'];
        $descripcion .= ' '.$registro['inm_doc_ubicacion_id'];
        return $descripcion;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $registro = $this->registro(registro_id: $id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener registro', data: $registro);
        }

        $elimina = parent::elimina_bd($id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar prospecto documento', data: $elimina);
        }

        $documento = (new inm_doc_ubicacion(link: $this->link))->elimina_bd(id: $registro['inm_doc_ubicacion_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar documento', data: $documento);
        }

        return $elimina;
    }


    private function valida_alta_relacion(array $registro){

        $keys = array('inm_transferencia_id','inm_doc_ubicacion_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }
        return true;
    }
}