<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_bitacora_status_prospecto extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_bitacora_status_prospecto';
        $columnas = array($tabla=>false,'inm_status_prospecto'=>$tabla,'inm_prospecto'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Bitacora Status Prospecto';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_prospecto_id'];
            $descripcion .= ' '.$this->registro['inm_status_prospecto_id'];
            $descripcion .= ' '.$this->registro['fecha_status'];
            $this->registro['descripcion'] = $descripcion;
        }

        if(!isset($this->registro['codigo'])){
            $descripcion = $this->registro['inm_prospecto_id'];
            $descripcion .= ' '.$this->registro['inm_status_prospecto_id'];
            $descripcion .= ' '.$this->registro['fecha_status'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_alta_bd);
        }

        $regitros_mod['inm_status_prospecto_id'] = $this->registro['inm_status_prospecto_id'];
        $r_modifica_bd = (new inm_prospecto(link: $this->link))->modifica_bd(registro: $regitros_mod,
            id: $this->registro['inm_prospecto_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al ajustar status de prospecto',data:  $r_modifica_bd);
        }

        return $r_alta_bd;
    }

}