<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\cat_sat\models\cat_sat_cve_prod;
use gamboamartin\cat_sat\models\cat_sat_unidad;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_producto extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_producto';
        $columnas = array($tabla=>false,'cat_sat_unidad'=>$tabla,'cat_sat_cve_prod'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Producto';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $r_cat_sat_unidad = (new cat_sat_unidad(link: $this->link))->registro(
            registro_id: $this->registro['cat_sat_unidad_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_cat_sat_unidad);
        }

        $r_cat_sat_cve_prod = (new cat_sat_cve_prod(link: $this->link))->registro(
            registro_id: $this->registro['cat_sat_cve_prod_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_cat_sat_cve_prod);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_cat_sat_cve_prod['cat_sat_cve_prod_descricion'];
            $descripcion .= ' '. $r_cat_sat_unidad['cat_sat_unidad_descripcion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }
}