<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_beneficiario extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_beneficiario';
        $columnas = array($tabla=>false,'inm_tipo_beneficiario'=>$tabla, 'inm_parentesco'=>$tabla);

        $campos_obligatorios = array('inm_tipo_beneficiario_id','inm_parentesco_id');

        $columnas_extra= array();
        $sql = "(SELECT
                    IFNULL(inm_rel_beneficiario_comprador.inm_comprador_id, -1)
                FROM
                    inm_rel_beneficiario_comprador
                    WHERE inm_rel_beneficiario_comprador.inm_beneficiario_id = inm_beneficiario.id
                )";

        $columnas_extra['inm_comprador_id'] = $sql;

        $sql = "(SELECT
                    IFNULL(inm_rel_beneficiario_prospecto.inm_prospecto_id, -1)
                FROM
                    inm_rel_beneficiario_prospecto
                    WHERE inm_rel_beneficiario_prospecto.inm_beneficiario_id = inm_beneficiario.id
                )";

        $columnas_extra['inm_prospecto_id'] = $sql;
        
        $renombres = array();

        $atributos_criticos = array('inm_tipo_beneficiario_id','inm_parentesco_id');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Beneficiarios';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $keys = array('inm_tipo_beneficiario_id','inm_parentesco_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_tipo_beneficiario_id'];
            $descripcion .= ' '.$this->registro['inm_parentesco_id'];
            $descripcion .= ' '.$this->registro['nombre'];
            $descripcion .= ' '.$this->registro['apellido_paterno'];
            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar', data: $r_alta_bd);
        }


        return $r_alta_bd;

    }

    public function elimina_bd(int $id): array|stdClass
    {
        $rel_bene = (new inm_rel_beneficiario_comprador(link: $this->link))->filtro_and(
            filtro: array('inm_beneficiario_id' => $id));
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener bitacora status comp',data:  $rel_bene);
        }

        $inm_bit_comp = (new inm_bitacora_status_comprador(link: $this->link))->existe_status_comprador(
            inm_comprador_id: $rel_bene->registros[0]['inm_comprador_id'], values: array('11'));
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener bitacora status comp',data:  $inm_bit_comp);
        }

        if ($inm_bit_comp->n_registros > 0) {
            return $this->error->error(mensaje: 'Error el cliente ya esta cancelado',data:  $inm_bit_comp);
        }

        $documento_etapa = (new inm_rel_beneficiario_comprador(link: $this->link))->elimina_con_filtro_and(
            filtro: array('inm_beneficiario_id' => $id));
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar documento etapa', data: $documento_etapa);
        }

        $elimina = parent::elimina_bd($id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar prospecto documento', data: $elimina);
        }

        return $elimina;
    }

}