<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_rel_costo_cheque extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_costo_cheque';
        $columnas = array($tabla=>false,'inm_costo'=>$tabla, 'inm_cheque'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'cheque';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' '.$this->registro['numero_cheque'];
            $this->registro['descripcion'] = $descripcion;
        }

        if(!isset($this->registro['codigo'])){
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' '.$this->registro['numero_cheque'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_alta_bd);
        }
/*
        if($this->registro['inm_tipo_cheque_id'] === 1){
            $registro = array();
            $registro['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro['inm_concepto_id'] = 19;
            $registro['monto'] = $this->registro['monto'];
            $registro['fecha'] = date('Y-m-d');
            $registro['referencia'] = $this->registro['nombre_beneficiario'];
            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(
                registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }
        }else if($this->registro['inm_tipo_cheque_id'] === 2){
            $registro = array();
            $registro['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro['inm_concepto_id'] = 36;
            $registro['monto'] = $this->registro['monto'];
            $registro['referencia'] = $this->registro['nombre_beneficiario'];
            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(
                registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }
        }*/

        return $r_alta_bd;
    }
    /*
    public function modifica_bd(array $registro, int $id, bool $reactiva = false, array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id,reactiva:  $reactiva,
            keys_integra_ds:  $keys_integra_ds);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar descripcion',data:  $r_modifica_bd);
        }

        if($this->registro['inm_tipo_cheque_id'] === 1){
            $registro = array();
            $registro['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro['inm_concepto_id'] = 19;
            $registro['monto'] = $this->registro['monto'];
            $registro['fecha'] = date('Y-m-d');
            $registro['referencia'] = $this->registro['nombre_beneficiario'];
            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(
                registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }
        }else if($this->registro['inm_tipo_cheque_id'] === 2){
            $registro = array();
            $registro['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro['inm_concepto_id'] = 36;
            $registro['monto'] = $this->registro['monto'];
            $registro['referencia'] = $this->registro['nombre_beneficiario'];
            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(
                registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }
        }

        return $r_modifica_bd;
    }*/

    public function elimina_bd(int $id): array|stdClass
    {
        $r_costo = $this->registro(registro_id: $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener costoacion',data:  $r_costo);
        }

        $r_elimina_bd = parent::elimina_bd(id:  $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar descripcion',data:  $r_elimina_bd);
        }

        $modelo_inm_costo = new inm_costo(link: $this->link);
        $filtro['inm_costo.id'] = $r_costo['inm_costo_id'];
        $r_rel = $modelo_inm_costo->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener relacion',data:  $r_rel);
        }

        if($r_rel->n_registros > 0) {
            $r_elimina = $modelo_inm_costo->elimina_bd(id: $r_rel->registros[0]['inm_costo_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener costoacion', data: $r_elimina);
            }
        }

        return $r_elimina_bd;
    }

}