<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_rel_emp_emp extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_emp_emp';
        $columnas = array($tabla=>false,'inm_empleado'=>$tabla,'em_empleado'=>$tabla);

        $campos_obligatorios = array();
        $columnas_extra= array();
        $renombres= array();
        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion Empleado';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' ' . $this->registro['inm_transferencia_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' ' . $this->registro['inm_transferencia_id'] . rand();
            $this->registro['codigo'] = $descripcion;
        }
        

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $filtro = array();
        $filtro['inm_rel_emp_emp.id'] = $id;
        $r_rel = $this->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener relacion',data:  $r_rel);
        }

        if($r_rel->n_registros > 0) {
            $modelo_inm_doc = new inm_rel_doc_transferencia_ubicacion(link: $this->link);

            $filtro = array();
            $filtro['inm_transferencia.id'] = $r_rel->registros[0]['inm_transferencia_id'];
            $r_doc = $modelo_inm_doc->filtro_and(filtro: $filtro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener relacion documento', data: $r_doc);
            }

            if ($r_doc->n_registros > 0) {
                return $this->error->error(mensaje: 'Error al existe un documento de poliza transferencia',
                    data: $r_doc);
            }
        }

        $r_elimina_bd = parent::elimina_bd(id:  $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar descripcion',data:  $r_elimina_bd);
        }

        if($r_rel->n_registros > 0) {
            $r_elimina = (new inm_transferencia(link: $this->link))->elimina_bd(
                id: $r_rel->registros[0]['inm_transferencia_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener relacion', data: $r_elimina);
            }
        }

        return $r_elimina_bd;
    }
}