<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_ubicacion_etapa extends _inm_ubicaciones {
    public function __construct(PDO $link)
    {
        $tabla = 'inm_ubicacion_etapa';
        $columnas = array($tabla=>false,'pr_etapa_proceso'=>$tabla,'inm_ubicacion'=>$tabla,
            'pr_proceso'=>'pr_etapa_proceso','pr_etapa'=>'pr_etapa_proceso');

        $campos_obligatorios = array('pr_etapa_proceso_id','inm_ubicacion_id','fecha');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('pr_etapa_proceso_id','inm_ubicacion_id','fecha');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Etapas de Ubicacion';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar ubicacion',data:  $r_alta_bd);
        }


        $row_udp['etapa'] = $r_alta_bd->registro_obj->pr_etapa_descripcion;
        $upd = (new inm_ubicacion(link: $this->link))->modifica_bd(registro: $row_udp,
            id: $r_alta_bd->registro_obj->inm_ubicacion_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al actualizar etapa', data: $upd);
        }


        return $r_alta_bd;
    }


    final public function init_row(string $key_entidad_base_id, string $key_entidad_id, array $registro): array{


        if(!isset($registro['descripcion'])){

            $registro = $this->integra_descripcion(registro:  $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al integrar descripcion',data:  $registro);
            }

        }
        return $registro;
    }

    private function integra_descripcion(array $registro){

        $descripcion = $this->descripcion(key_entidad_base_id: 'inm_ubicacion_id',
            key_entidad_id: 'pr_etapa_proceso_id', registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener descripcion',data:  $descripcion);
        }


        $registro['descripcion'] = $descripcion;
        return $registro;
    }




}