<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_movimiento_consumo extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_movimiento_consumo';
        $columnas = array($tabla=>false,'inm_ubicacion'=>$tabla,'inm_producto'=>$tabla,
            'inm_detalle_factura_compra'=>$tabla,'inm_concepto'=>'inm_producto',
            'inm_factura_compra'=>'inm_detalle_factura_compra');

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Movimiento Consumo';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_inm_ubicacion = (new inm_ubicacion(link: $this->link))->registro(
            registro_id: $this->registro['inm_ubicacion_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_ubicacion);
        }

        $r_inm_producto = (new inm_producto(link: $this->link))->registro(
            registro_id: $this->registro['inm_producto_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_producto);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_inm_ubicacion['inm_ubicacion_ubicacion'];
            $descripcion .= ' '. $r_inm_producto['inm_producto_descripcion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        $r_inm_detalle_factura_compra = (new inm_detalle_factura_compra(link: $this->link))->registro(
            registro_id: $this->registro['inm_detalle_factura_compra_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_detalle_factura_compra);
        }

        $filtro['inm_movimiento_consumo.inm_detalle_factura_compra_id'] = $this->registro['inm_detalle_factura_compra_id'];
        $r_movimientos_consumo = $this->filtro_and(filtro: $filtro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_movimientos_consumo);
        }

        if($r_movimientos_consumo->n_registros > 0){
            $suma = 0;
            foreach ($r_movimientos_consumo->registros as $registro){
                $suma += $registro['inm_movimiento_consumo_cantidad'];
            }

            if((float)$suma === (float)$r_inm_detalle_factura_compra['inm_detalle_factura_compra_cantidad']){
                $registro_mod['asignado_completo'] = 'activo';

                $r_modifica = (new inm_detalle_factura_compra(link: $this->link))->modifica_bd(registro: $registro_mod,
                    id: $this->registro['inm_detalle_factura_compra_id']);
                if (errores::$error) {
                    return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_modifica);
                }
            }
        }

        $filtro_fact['inm_factura_compra.id'] = $r_inm_detalle_factura_compra['inm_factura_compra_id'];
        $filtro_fact['inm_detalle_factura_compra.asignado_completo'] = 'inactivo';
        $r_inm_detalle_fac = (new inm_detalle_factura_compra(link: $this->link))->filtro_and(filtro: $filtro_fact);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_detalle_fac);
        }

        if($r_inm_detalle_fac->n_registros <= 0){
            $registro_mod_fac['asignado_completo'] = 'activo';

            $r_modifica = (new inm_factura_compra(link: $this->link))->modifica_bd(registro: $registro_mod_fac,
                id: $r_inm_detalle_factura_compra['inm_factura_compra_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_modifica);
            }
        }

        $filtro_costo['inm_ubicacion.id'] = $this->registro['inm_ubicacion_id'];
        $filtro_costo['inm_concepto.id'] = $r_inm_producto['inm_concepto_id'];
        $r_inm_costo = (new inm_costo(link: $this->link))->filtro_and(filtro: $filtro_costo);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_inm_costo);
        }

        if($r_inm_costo->n_registros > 0){
            $registro_che = array();
            $registro_che['monto'] = $r_inm_costo->registros[0]['inm_costo_monto'] + $this->registro['total'];

            $r_costo = (new inm_costo(link: $this->link))->modifica_bd(registro: $registro_che,
                id: $r_inm_costo->registros[0]['inm_costo_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_costo);
            }
        }else{
            $registro_che = array();
            $registro_che['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro_che['monto'] = $this->registro['total'];
            $registro_che['fecha'] = date('Y-m-d');
            $registro_che['referencia'] = $r_inm_ubicacion['inm_ubicacion_razon_social'];
            $registro_che['inm_concepto_id'] = $r_inm_producto['inm_concepto_id'];

            $r_costo = (new inm_costo(link: $this->link))->alta_registro(registro: $registro_che);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_costo);
            }
        }

        return $r_alta_bd;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $registro_mov = (new inm_movimiento_consumo(link: $this->link))->registro(registro_id: $id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $registro_mov);
        }

        $r_inm_detalle_factura_compra = (new inm_detalle_factura_compra(link: $this->link))->registro(
            registro_id: $registro_mov['inm_detalle_factura_compra_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_detalle_factura_compra);
        }

        $r_elimina_bd = parent::elimina_bd(id:  $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar descripcion',data:  $r_elimina_bd);
        }

        $filtro['inm_movimiento_consumo.inm_detalle_factura_compra_id'] = $registro_mov['inm_detalle_factura_compra_id'];
        $r_movimientos_consumo = $this->filtro_and(filtro: $filtro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_movimientos_consumo);
        }

        $suma = 0;
        foreach ($r_movimientos_consumo->registros as $registro){
            $suma += $registro['inm_movimiento_consumo_cantidad'];
        }

        if((float)$suma < (float)$r_inm_detalle_factura_compra['inm_detalle_factura_compra_cantidad']){
            $registro_mod['asignado_completo'] = 'inactivo';

            $r_modifica = (new inm_detalle_factura_compra(link: $this->link))->modifica_bd(registro: $registro_mod,
                id: $registro_mov['inm_detalle_factura_compra_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_modifica);
            }
        }

        $filtro_fact['inm_factura_compra.id'] = $r_inm_detalle_factura_compra['inm_factura_compra_id'];
        $filtro_fact['inm_detalle_factura_compra.asignado_completo'] = 'inactivo';
        $r_inm_detalle_fac = (new inm_detalle_factura_compra(link: $this->link))->filtro_and(filtro: $filtro_fact);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_detalle_fac);
        }

        if($r_inm_detalle_fac->n_registros > 0){
            $registro_mod_fac['asignado_completo'] = 'inactivo';

            $r_modifica = (new inm_factura_compra(link: $this->link))->modifica_bd(registro: $registro_mod_fac,
                id: $r_inm_detalle_factura_compra['inm_factura_compra_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_modifica);
            }
        }

        $filtro_costo['inm_ubicacion.id'] = $registro_mov['inm_ubicacion_id'];
        $filtro_costo['inm_concepto.id'] = $registro_mov['inm_concepto_id'];
        $r_inm_costo = (new inm_costo(link: $this->link))->filtro_and(filtro: $filtro_costo);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_inm_costo);
        }

        if($r_inm_costo->n_registros > 0){
            $registro_che = array();
            $registro_che['monto'] = $r_inm_costo->registros[0]['inm_costo_monto'] -
                $registro_mov['inm_movimiento_consumo_total'];

            $r_costo = (new inm_costo(link: $this->link))->modifica_bd(registro: $registro_che,
                id: $r_inm_costo->registros[0]['inm_costo_id']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_costo);
            }

            if($registro_che['monto'] <= 0){
                $r_elimina = (new inm_costo(link: $this->link))->elimina_bd(id:
                    $r_inm_costo->registros[0]['inm_costo_id']);
                if (errores::$error) {
                    return $this->error->error(mensaje: 'Error al obtener relacion', data: $r_elimina);
                }
            }
        }

        return $r_elimina_bd;
    }
}