<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_reparacion extends _modelo_parent {
    public function __construct(PDO $link)
    {
        $tabla = 'inm_reparacion';

        $columnas = array($tabla => false, 'inm_ubicacion' => $tabla, 'inm_responsable' => $tabla);

        $campos_obligatorios = array('inm_ubicacion_id', 'inm_responsable_id', 'descripcion');

        $columnas_extra = array();
        $renombres = array();

        $atributos_criticos = array('inm_ubicacion_id', 'inm_responsable_id', 'descripcion');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Reparaciones';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $filtro['inm_ubicacion.id'] = $this->registro['inm_ubicacion_id'];
        $filtro['inm_responsable.id'] = $this->registro['inm_responsable_id'];
        $r_reparacion = $this->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_reparacion);
        }

        if($r_reparacion->n_registros > 0){
            $registro_puro = $this->registro(registro_id: $r_reparacion->registros[0]['inm_reparacion_id'],
                columnas_en_bruto: true,retorno_obj: true);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener relacion', data: $registro_puro);
            }

            return $this->data_result_transaccion(
                mensaje: "Ya existe una reparacion asignada a este responsable",
                registro: $r_reparacion->registros[0],
                registro_ejecutado: $this->registro,
                registro_id: $r_reparacion->registros[0]['inm_reparacion_id'],
                registro_original: $r_reparacion->registros[0],
                registro_puro: $registro_puro,
                sql: 'Registro existente'
            );
        }

        $inm_ubicacion = (new inm_ubicacion(link: $this->link))->registro(
            registro_id: $this->registro['inm_ubicacion_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $inm_ubicacion);
        }
        
        $inm_responsable = (new inm_responsable(link: $this->link))->registro(
            registro_id: $this->registro['inm_responsable_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $inm_responsable);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $inm_responsable['inm_responsable_descripcion'];
            $descripcion .= ' ' .  $inm_ubicacion['inm_ubicacion_ubicacion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $inm_responsable['inm_responsable_descripcion'];
            $descripcion .= ' ' .  $inm_ubicacion['inm_ubicacion_ubicacion'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }
}

