<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_periodo_asistencia extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_periodo_asistencia';
        $columnas = array($tabla=>false);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Periodo Asistencia';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('fecha_inicio','fecha_fin');
        $valida = $this->validacion->fechas_in_array(data: $this->registro,keys:  $keys);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if (!isset( $this->registro['descripcion'])) {
            $descripcion = 'Periodo Inicial: '. $this->registro['fecha_inicio'];
            $descripcion .= ' - Periodo Final: ' .  $this->registro['fecha_fin'];
            $this->registro['descripcion'] = $descripcion;
        }
        
        if (!isset( $this->registro['descripcion_select'])) {
            $descripcion_select = 'Periodo Inicial: '. $this->registro['fecha_inicio'];
            $descripcion_select .= ' - Periodo Final: ' .  $this->registro['fecha_fin'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($this->registro['codigo'])) {
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('fecha_inicio','fecha_fin');
        $valida = $this->validacion->fechas_in_array(data: $registro,keys:  $keys);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }
        
        if (!isset($registro['descripcion'])) {
            $descripcion = 'Periodo Inicial: '.$registro['fecha_inicio'];
            $descripcion .= ' - Periodo Final: ' . $registro['fecha_fin'];
            $registro['descripcion'] = $descripcion;
        }

        if (!isset( $registro['descripcion_select'])) {
            $descripcion_select = 'Periodo Inicial: '. $registro['fecha_inicio'];
            $descripcion_select .= ' - Periodo Final: ' .  $registro['fecha_fin'];
            $registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($registro['codigo'])) {
            $codigo = $registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $registro['codigo'] = $codigo;
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}