<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\administrador\models\adm_usuario;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_empleado extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_empleado';
        $columnas = array($tabla=>false,'adm_usuario'=>$tabla,'inm_horario'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Empleado';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('adm_usuario_id','inm_horario_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $keys = array('nombre','apellido_paterno');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['adm_usuario_id'];
            $descripcion .= ' - ' .  $this->registro['inm_horario_id'];
            $descripcion .= ' - ' .  $this->registro['nombre'];
            $descripcion .= ' ' .  $this->registro['apellido_paterno'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset( $this->registro['razon_social'])) {
            $razon_social = $this->registro['nombre'];
            $razon_social .= ' ' . $this->registro['apellido_paterno'];
            if(isset($this->registro['apellido_materno'])  && trim($this->registro['apellido_materno'])!==''){
                $razon_social .= ' ' . $this->registro['apellido_materno'];
            }
            $this->registro['razon_social'] = $razon_social;
        }

        if (!isset( $this->registro['descripcion_select'])) {
            $descripcion_select = $this->registro['razon_social'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($this->registro['codigo'])) {
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('adm_usuario_id','inm_horario_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $keys = array('nombre','apellido_paterno');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if (!isset($registro['descripcion'])) {
            $descripcion = $registro['adm_usuario_id'];
            $descripcion .= ' - ' .  $registro['inm_horario_id'];
            $descripcion .= ' - ' .  $registro['nombre'];
            $descripcion .= ' ' .  $registro['apellido_paterno'];
            $registro['descripcion'] = $descripcion;
        }

        if (!isset( $registro['razon_social'])) {
            $razon_social = $registro['nombre'];
            $razon_social .= ' ' . $registro['apellido_paterno'];
            if(isset($registro['apellido_materno'])  && trim($registro['apellido_materno'])!==''){
                $razon_social .= ' ' . $registro['apellido_materno'];
            }
            $registro['razon_social'] = $razon_social;
        }

        if (!isset( $registro['descripcion_select'])) {
            $descripcion_select = $registro['razon_social'];
            $registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($registro['codigo'])) {
            $codigo = $registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $registro['codigo'] = $codigo;
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }


    public function valida_usuario(string $password, string $usuario){
        if($usuario === ''){
            return $this->error->error(mensaje: 'El usuario no puede ir vacio',data: $usuario);
        }

        if($password === ''){
            return $this->error->error(mensaje: 'El $password no puede ir vacio',data: $password);
        }

        $filtro['adm_usuario.user'] = $usuario;
        $filtro['adm_usuario.password'] = $password;
        $filtro['adm_usuario.status'] = 'activo';

        $r_usuario = $this->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener usuario',data: $r_usuario);
        }

        if((int)$r_usuario->n_registros === 0){
            return $this->error->error(mensaje: 'Error al validar usuario y pass ',data: $usuario);
        }
        if((int)$r_usuario->n_registros > 1){
            return $this->error->error(mensaje: 'Error al validar usuario y pass ',data: $usuario);
        }

        return $r_usuario->registros[0];
    }
}