<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use config\generales;
use gamboamartin\documento\models\doc_tipo_documento;
use gamboamartin\errores\errores;
use gamboamartin\notificaciones\models\not_rel_mensaje;
use PDO;
use stdClass;

class inm_periodo_asistencia extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_periodo_asistencia';
        $columnas = array($tabla=>false,'inm_horario' => $tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Periodo Asistencia';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('inm_horario_id');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys, registro: $this->registro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
        }

        $registro_horario = (new inm_horario(link: $this->link))->registro(
            registro_id: $this->registro['inm_horario_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al validar registro', data: $registro_horario);
        }

        $filtro['inm_horario.id'] = $this->registro['inm_horario_id'];
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['operador'] = '<=';
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['valor'] = 'inm_periodo_asistencia.fecha_fin';
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['comparacion'] = 'AND';
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['valor_es_campo'] = true;

        $filtro_especial[1][(string)$this->registro['fecha_fin']]['operador'] = '>=';
        $filtro_especial[1][(string)$this->registro['fecha_fin']]['valor'] = 'inm_periodo_asistencia.fecha_inicio';
        $filtro_especial[1][(string)$this->registro['fecha_fin']]['comparacion'] = 'AND';
        $filtro_especial[1][(string)$this->registro['fecha_fin']]['valor_es_campo'] = true;
        $r_filtro_periodo = $this->filtro_and(filtro: $filtro, filtro_especial: $filtro_especial);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
        }

        if ($r_filtro_periodo->n_registros > 0) {
            return $this->error->error(mensaje: 'Error ya existe un periodo del horario ' .
                $registro_horario['inm_horario_descripcion'] .
                ' que entra en el mismo rengo de fechas que se intenta insertar', data: $valida);
        }

        $keys = array('fecha_inicio','fecha_fin');
        $valida = $this->validacion->fechas_in_array(data: $this->registro,keys:  $keys);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $registro_horario['inm_horario_descripcion'];
            $descripcion .= ' - Periodo Inicial: '. $this->registro['fecha_inicio'];
            $descripcion .= ' - Periodo Final: ' .  $this->registro['fecha_fin'];
            $this->registro['descripcion'] = $descripcion;
        }
        
        if (!isset( $this->registro['descripcion_select'])) {
            $descripcion_select = $registro_horario['inm_horario_descripcion'];
            $descripcion_select .= ' - Periodo Inicial: '. $this->registro['fecha_inicio'];
            $descripcion_select .= ' - Periodo Final: ' .  $this->registro['fecha_fin'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($this->registro['codigo'])) {
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function envia_reporte(int $registro_id){
        $filtro_tipo['doc_tipo_documento.descripcion'] = "REPORTE ASISTENCIA";
        $r_tipo_documento = (new doc_tipo_documento(link: $this->link))->filtro_and(filtro: $filtro_tipo);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener tipo documento', data: $r_tipo_documento);
        }

        if($r_tipo_documento->n_registros <= 0){
            return $this->error->error(mensaje: 'Error no existe tipo de documento valido', data: $r_tipo_documento);
        }

        $r_periodo_asistencia = (new inm_periodo_asistencia(link: $this->link))->registro(registro_id: $registro_id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener xls', data: $r_periodo_asistencia);
        }

        $generales = new generales();
        $result = (new inm_checada(link: $this->link))->genera_reporte(path_base: $generales->path_base, registro_id: $registro_id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener xls', data: $result);
        }

        $decoded_data = base64_decode($result);
        $file_path = $generales->path_base."archivos/temporales/reporte_asistencia.xlsx";
        file_put_contents($file_path, $decoded_data);

        $_FILES['documento'] = [
            'name' => basename($file_path),
            'type' => mime_content_type($file_path),
            'tmp_name' => $file_path,
            'error' => 0,
            'size' => filesize($file_path)
        ];

        $registro_doc['inm_periodo_asistencia_id'] = $registro_id;
        $registro_doc['doc_tipo_documento_id'] = $r_tipo_documento->registros[0]['doc_tipo_documento_id'];

        $r_inm_doc_periodo_asistencia = (new inm_doc_periodo_asistencia(link:$this->link))->alta_registro(registro: $registro_doc);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al convertir en cliente', data: $r_inm_doc_periodo_asistencia);
        }

        $inserta_notificacion = (new _email(link: $this->link))->inserta_mensaje(link: $this->link,
            row_entidad: $r_periodo_asistencia);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar notificacion',data:  $inserta_notificacion);
        }

        $inserta_adjunto = (new _email(link: $this->link))->inserta_adjunto(
            doc: $r_inm_doc_periodo_asistencia->registro, not_mensaje_id: $inserta_notificacion, link: $this->link);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar notificacion',data:  $inserta_adjunto);
        }

        $filtro['not_mensaje.id'] = $inserta_notificacion;
        $r_not_rel_mensaje =  (new not_rel_mensaje(link: $this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener mensajes',data:  $r_not_rel_mensaje);
        }

        $envios = array();
        foreach ($r_not_rel_mensaje->registros as $not_rel_mensaje){
            $envios[] = (new _email(link: $this->link))->notifica(not_mensaje: $not_rel_mensaje,link: $this->link);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al insertar notificacion',data:  $envios);
            }
        }

        $registro_mod['inm_periodo_asistencia.enviado'] = 'activo';
        $r_inm_periodo_asistencia = (new inm_periodo_asistencia(link: $this->link))->modifica_bd(
            registro: $registro_mod,id: $registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar notificacion',data:  $r_inm_periodo_asistencia);
        }

        return $result;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($registro['status'])){
            $keys = array('inm_horario_id');
            $valida = $this->validacion->valida_existencia_keys(keys:  $keys, registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
            }

            $registro_horario = (new inm_horario(link: $this->link))->registro(
                registro_id: $registro['inm_horario_id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al validar registro',data:  $registro_horario);
            }

            $keys = array('fecha_inicio','fecha_fin');
            $valida = $this->validacion->fechas_in_array(data: $registro,keys:  $keys);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
            }

            if (!isset($registro['descripcion'])) {
                $descripcion = $registro_horario['inm_horario_descripcion'];
                $descripcion .= ' - Periodo Inicial: '. $registro['fecha_inicio'];
                $descripcion .= ' - Periodo Final: ' .  $registro['fecha_fin'];
                $registro['descripcion'] = $descripcion;
            }

            if (!isset( $registro['descripcion_select'])) {
                $descripcion_select = $registro_horario['inm_horario_descripcion'];
                $descripcion_select .= ' - Periodo Inicial: '. $registro['fecha_inicio'];
                $descripcion_select .= ' - Periodo Final: ' .  $registro['fecha_fin'];
                $registro['descripcion_select'] = $descripcion_select;
            }

            if (!isset($registro['codigo'])) {
                $codigo = $registro['descripcion'];
                $codigo .= ' ' . rand(10000,99999);
                $registro['codigo'] = $codigo;
            }
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}