<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_llave extends _modelo_parent {
    public function __construct(PDO $link)
    {
        $tabla = 'inm_llave';
        $columnas = array($tabla => false, 'inm_ubicacion' => $tabla);

        $campos_obligatorios = array('inm_ubicacion_id', 'descripcion');

        $columnas_extra = array();
        $renombres = array();

        $atributos_criticos = array('inm_ubicacion_id', 'descripcion');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Llaves';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion']. rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }
}

