<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use config\generales;
use gamboamartin\documento\models\doc_documento;
use gamboamartin\documento\models\doc_documento_etapa;
use gamboamartin\errores\errores;
use gamboamartin\inmuebles\controllers\_doctos;
use PDO;
use stdClass;


class inm_doc_factura_compra extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_doc_factura_compra';
        $columnas = array($tabla=>false,'inm_factura_compra'=>$tabla,'doc_documento'=>$tabla,
            'doc_tipo_documento'=>'doc_documento','doc_extension'=>'doc_documento');

        $campos_obligatorios = array('inm_factura_compra_id','doc_documento_id');

        $columnas_extra= array();
        $sql = "(SELECT inm_dropbox_ruta.id_dropbox FROM inm_dropbox_ruta WHERE inm_dropbox_ruta.doc_documento_id = doc_documento.id)";
        $columnas_extra['inm_dropbox_ruta_id_dropbox'] = $sql;

        $renombres= array();

        $atributos_criticos = array('inm_factura_compra_id','doc_documento_id');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Documentos de comprador';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $registro_doc['doc_tipo_documento_id'] = $this->registro['doc_tipo_documento_id'];
        $file = $_FILES['documento'];

        if((new generales())->guarda_archivo_dropbox) {
            $registro_doc['ruta_relativa'] = 'inm_factura_compra/'.$this->registro['inm_factura_compra_id'].'/';
        }
        $r_alta_doc = (new doc_documento(link: $this->link))->alta_documento(registro: $registro_doc,file: $file);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar doc',data:  $r_alta_doc);
        }

        $this->registro['doc_documento_id'] = $r_alta_doc->registro_id;

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->descripcion(r_alta_doc: $r_alta_doc,registro:  $this->registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener descripcion',data:  $descripcion);
            }
            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }

    private function descripcion(stdClass $r_alta_doc, array $registro): string
    {
        $descripcion = $r_alta_doc->registro_id;
        $descripcion .= ' '.$registro['doc_tipo_documento_id'];
        $descripcion .= ' '.$r_alta_doc->registro_obj->doc_tipo_documento_descripcion;
        $descripcion .= ' '.$r_alta_doc->registro_obj->doc_extension_descripcion;
        $descripcion .= ' '.$registro['inm_factura_compra_id'];
        $descripcion .= ' '.$r_alta_doc->registro_obj->doc_documento_nombre;
        return $descripcion;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $registro = $this->registro(registro_id: $id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener registro', data: $registro);
        }

        $documento_etapa = (new doc_documento_etapa(link: $this->link))->elimina_con_filtro_and(filtro: array('doc_documento_id' => $registro['doc_documento_id']));
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar documento etapa', data: $documento_etapa);
        }

        $elimina = parent::elimina_bd($id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar prospecto documento', data: $elimina);
        }

        $documento = (new doc_documento(link: $this->link))->elimina_bd(id: $registro['doc_documento_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar documento', data: $documento);
        }

        return $elimina;
    }

    final public function inm_docs_comprador(int $inm_factura_compra_id, array $tipos_documentos)
    {
        $in = array();

        if (count($tipos_documentos) > 0) {
            $in['llave'] = 'doc_documento.doc_tipo_documento_id';
            $in['values'] = $tipos_documentos;
        }

        $r_inm_doc_prospecto = $this->filtro_and(filtro: array('inm_factura_compra.id' => $inm_factura_compra_id,
            'inm_doc_factura_compra.es_foto' => 'inactivo'), in: $in);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener documentos', data: $r_inm_doc_prospecto);
        }

        return $r_inm_doc_prospecto->registros;
    }

    public function obten_documento(int $inm_factura_compra_id)
    {
        $filtro['inm_factura_compra.id'] = $inm_factura_compra_id;
        $order = array('inm_factura_compra.id'=>'DESC');
        $r_inm_factura_compra = $this->filtro_and(filtro: $filtro, order: $order);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener documentos', data: $r_inm_factura_compra);
        }

        if($r_inm_factura_compra->n_registros <= 0){
            return $this->error->error(mensaje: 'Error al obtener documentos', data: $r_inm_factura_compra);
        }

        $path = $r_inm_factura_compra->registros[0]['doc_documento_ruta_absoluta'];

        if((new generales())->guarda_archivo_dropbox) {
            $filtro_drop['doc_documento.id'] = $r_inm_factura_compra->registros[0]['doc_documento_id'];
            $r_inm_dropbox_ruta = (new inm_dropbox_ruta(link: $this->link))->filtro_and(filtro: $filtro_drop);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener documentos', data: $r_inm_dropbox_ruta);
            }

            if($r_inm_dropbox_ruta->n_registros > 0) {
                $reg = $r_inm_dropbox_ruta->registros[0];
                $guarda = (new _dropbox(link: $this->link))->preview(
                    dropbox_id: $reg['inm_dropbox_ruta_id_dropbox'], extencion: $reg['doc_extension_descripcion']);
                if (errores::$error) {
                    return $this->error->error(mensaje: 'Error al obtener documentos', data: $guarda);
                }

                $path = (new generales())->path_base . $guarda->ruta_archivo;
            }
        }

        return $path;
    }

}