<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_movimiento_consumo extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_movimiento_consumo';
        $columnas = array($tabla=>false,'inm_ubicacion'=>$tabla,'inm_producto'=>$tabla,
            'inm_detalle_factura_compra'=>$tabla,'inm_concepto'=>'inm_producto');

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Movimiento Consumo';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_inm_ubicacion = (new inm_ubicacion(link: $this->link))->registro(
            registro_id: $this->registro['inm_ubicacion_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_ubicacion);
        }

        $r_inm_producto = (new inm_producto(link: $this->link))->registro(
            registro_id: $this->registro['inm_producto_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_producto);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_inm_ubicacion['inm_ubicacion_ubicacion'];
            $descripcion .= ' '. $r_inm_producto['inm_producto_descripcion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }
}