<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_rel_efectivo_comprador extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_efectivo_comprador';
        $columnas = array($tabla=>false,'inm_efectivo'=>$tabla,'inm_comprador'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion efectivo';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['inm_efectivo_id'])) {
            $registro_efectivo = array();

            $registro_efectivo['monto'] = $this->registro['monto'];
            $registro_efectivo['nombre_beneficiario'] = $this->registro['nombre_beneficiario'];

            $r_inm_efectivo = (new inm_efectivo(link: $this->link))->alta_registro(registro: $registro_efectivo);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_efectivo);
            }

            $this->registro['inm_efectivo_id'] = $r_inm_efectivo->registro_id;

            $inm_ubicaciones = (new _inm_comprador())->inm_ubicaciones(
                inm_comprador_id: $this->registro['inm_comprador_id'], link:  $this->link);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $inm_ubicaciones);
            }

            $registro = array();
            $registro['inm_ubicacion_id'] = $inm_ubicaciones[0]['inm_ubicacion_id'];
            $registro['monto'] = $this->registro['monto'];
            $registro['fecha'] = date('Y-m-d');
            $registro['referencia'] = $this->registro['nombre_beneficiario'];
            $registro['inm_concepto_id'] = 19;

            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }

            $registro = array();
            $registro['inm_costo_id'] = $r_inm_costo->registro_id;
            $registro['inm_efectivo_id'] = $r_inm_efectivo->registro_id;
            $r_rel_costo_efectivo = (new inm_rel_costo_efectivo(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_rel_costo_efectivo);
            }


            unset($this->registro['monto'], $this->registro['nombre_beneficiario'],
                $this->registro['inm_tipo_efectivo_id'], $this->registro['numero_efectivo']);
        }


        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['inm_comprador_id'];
            $descripcion .= ' ' . $this->registro['inm_efectivo_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['inm_comprador_id'];
            $descripcion .= ' ' . $this->registro['inm_efectivo_id'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }
}