<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_rel_cheque_ubicacion extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_cheque_ubicacion';
        $columnas = array($tabla=>false,'inm_cheque'=>$tabla,'inm_ubicacion'=>$tabla,'inm_tipo_cheque'=>'inm_cheque',
            'bn_cuenta'=>'inm_cheque', 'dp_colonia_postal'=>'inm_ubicacion', 'dp_cp'=>'dp_colonia_postal',
            'dp_colonia'=>'dp_colonia_postal', 'dp_municipio'=>'dp_cp', 'dp_estado'=>'dp_municipio',
            'dp_pais'=>'dp_estado');

        $campos_obligatorios = array();

        $columnas_extra= array();
        $sql = "(CONCAT_WS(' ', inm_ubicacion.calle, inm_ubicacion.numero_exterior, 
        inm_ubicacion.numero_interior, dp_colonia.descripcion, dp_municipio.descripcion))";

        $columnas_extra['inm_ubicacion_ubicacion'] = $sql;

        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion Cheque';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['inm_cheque_id'])) {
            $registro_cheque = array();

            $registro_cheque['inm_ubicacion_id'] = $this->registro['inm_ubicacion_id'];
            $registro_cheque['monto'] = $this->registro['monto'];
            $registro_cheque['nombre_beneficiario'] = $this->registro['nombre_beneficiario'];
            $registro_cheque['inm_tipo_cheque_id'] = $this->registro['inm_tipo_cheque_id'];
            $registro_cheque['numero_cheque'] = '';

            if (isset($this->registro['numero_cheque'])) {
                $registro_cheque['numero_cheque'] = $this->registro['numero_cheque'];
            }

            $r_inm_cheque = (new inm_cheque(link: $this->link))->alta_registro(registro: $registro_cheque);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_cheque);
            }

            $this->registro['inm_cheque_id'] = $r_inm_cheque->registro_id;

            unset($this->registro['monto'], $this->registro['nombre_beneficiario'],
                $this->registro['inm_tipo_cheque_id'], $this->registro['numero_cheque']);
        }


        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' ' . $this->registro['inm_cheque_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= ' ' . $this->registro['inm_cheque_id'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }


}