<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\cat_sat\models\cat_sat_unidad;
use gamboamartin\errores\errores;
use gamboamartin\gastos\models\gt_proveedor;
use PDO;
use SimpleXMLElement;
use stdClass;


class inm_factura_compra extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_factura_compra';
        $columnas = array($tabla=>false,'gt_proveedor'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Factura Compra';
    }


    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $r_proveedor = (new gt_proveedor(link: $this->link))->registro(registro_id: $this->registro['gt_proveedor_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_proveedor);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_proveedor['gt_proveedor_razon_social'];
            $descripcion .= ' ' . $this->registro['fecha'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $r_proveedor['gt_proveedor_razon_social'];
            $descripcion .= ' ' . $this->registro['fecha'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_proveedor = (new gt_proveedor(link: $this->link))->registro(registro_id: $registro['gt_proveedor_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_proveedor);
        }

        if(!isset($registro['status'])){
            if (!isset($registro['descripcion'])) {
                $descripcion = $r_proveedor['gt_proveedor_razon_social'];
                $descripcion .= ' ' . $registro['fecha'];
                $registro['descripcion'] = $descripcion;
            }

            if (!isset($registro['codigo'])) {
                $descripcion = $r_proveedor['gt_proveedor_razon_social'];
                $descripcion .= ' ' . $registro['fecha'] . rand();
                $registro['codigo'] = $descripcion;
            }
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }

    /**
     * @throws \Exception
     */
    public function obten_registros_xml(int $inm_factura_compra_id): array
    {
        $path =  (new inm_doc_factura_compra(link:$this->link))->obten_documento(inm_factura_compra_id: $inm_factura_compra_id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $path);
        }

        //$xmlString = file_get_contents($_FILES['xml_factura']['tmp_name']);
        $xmlString = file_get_contents($path);

        $xml = new SimpleXMLElement($xmlString);
        $namespaces = $xml->getNamespaces(true);
        if(!isset($namespaces["cfdi"])){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $namespaces);
        }

        $conceptosXml = $xml->children($namespaces['cfdi'])->Conceptos->children($namespaces['cfdi'])->Concepto;

        $result = [];

        foreach ($conceptosXml as $concepto) {
            $attrs = $concepto->attributes();

            $conceptoData = [
                'ClaveProdServ' => (string)$attrs['ClaveProdServ'],
                'NoIdentificacion' => (string)$attrs['NoIdentificacion'],
                'Cantidad' => (string)$attrs['Cantidad'],
                'ClaveUnidad' => (string)$attrs['ClaveUnidad'],
                'Unidad' => (string)$attrs['Unidad'],
                'Descripcion' => (string)$attrs['Descripcion'],
                'ValorUnitario' => (string)$attrs['ValorUnitario'],
                'Importe' => (string)$attrs['Importe'],
                'Impuestos' => [
                    'Traslados' => [],
                    'Retenciones' => []
                ]
            ];

            $impuestosNode = $concepto->children($namespaces['cfdi'])->Impuestos;
            $conceptoData['Trasladado'] = 0;
            $conceptoData['Retenido'] = 0;

            if ($impuestosNode) {
                $trasladosNode = $impuestosNode->children($namespaces['cfdi'])->Traslados;
                if ($trasladosNode) {
                    foreach ($trasladosNode->children($namespaces['cfdi']) as $traslado) {
                        $tAttrs = $traslado->attributes();
                        $conceptoData['Impuestos']['Traslados'][] = [
                            'Base' => (string)$tAttrs['Base'],
                            'Impuesto' => (string)$tAttrs['Impuesto'],
                            'TipoFactor' => (string)$tAttrs['TipoFactor'],
                            'TasaOCuota' => (string)$tAttrs['TasaOCuota'],
                            'Importe' => (string)$tAttrs['Importe']
                        ];
                        $conceptoData['Trasladado'] += (float)$tAttrs['Importe'];
                    }
                }

                $retencionesNode = $impuestosNode->children($namespaces['cfdi'])->Retenciones;
                if ($retencionesNode) {
                    foreach ($retencionesNode->children($namespaces['cfdi']) as $retencion) {
                        $rAttrs = $retencion->attributes();
                        $conceptoData['Impuestos']['Retenciones'][] = [
                            'Base' => (string)$rAttrs['Base'],
                            'Impuesto' => (string)$rAttrs['Impuesto'],
                            'TipoFactor' => (string)$rAttrs['TipoFactor'],
                            'TasaOCuota' => (string)$rAttrs['TasaOCuota'],
                            'Importe' => (string)$rAttrs['Importe']
                        ];
                        $conceptoData['Retenido'] += (float)$rAttrs['Importe'];
                    }
                }
            }

            $conceptoData['Total'] = $conceptoData['Importe'] + $conceptoData['Trasladado'] - $conceptoData['Retenido'];

            $filtro_unidad['cat_sat_unidad.codigo'] = $attrs['ClaveUnidad'];
            $r_unidad = (new cat_sat_unidad(link: $this->link))->filtro_and(filtro: $filtro_unidad);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_unidad);

            }

            if($r_unidad->n_registros > 0){
                $conceptoData['Unidad'] = $r_unidad->registros[0]['cat_sat_unidad_descripcion'];
            }

            $result[] = $conceptoData;
        }

        return $result;
    }
}