<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\administrador\models\adm_usuario;
use gamboamartin\empleado\models\em_empleado;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_empleado extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_empleado';
        $columnas = array($tabla=>false,'adm_usuario'=>$tabla,'inm_horario'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Empleado';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('adm_usuario_id','inm_horario_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $keys = array('nombre','apellido_paterno');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['adm_usuario_id'];
            $descripcion .= ' - ' .  $this->registro['inm_horario_id'];
            $descripcion .= ' - ' .  $this->registro['nombre'];
            $descripcion .= ' ' .  $this->registro['apellido_paterno'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset( $this->registro['razon_social'])) {
            $razon_social = $this->registro['nombre'];
            $razon_social .= ' ' . $this->registro['apellido_paterno'];
            if(isset($this->registro['apellido_materno'])  && trim($this->registro['apellido_materno'])!==''){
                $razon_social .= ' ' . $this->registro['apellido_materno'];
            }
            $this->registro['razon_social'] = $razon_social;
        }

        if (!isset( $this->registro['descripcion_select'])) {
            $descripcion_select = $this->registro['razon_social'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($this->registro['codigo'])) {
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        $registro_emp['nombre'] = $this->registro['nombre'];
        $registro_emp['ap'] = $this->registro['apellido_paterno'];
        $registro_emp['am'] = $this->registro['apellido_materno'];
        if(isset($this->registro['rfc'])) {
            $registro_emp['rfc'] = $this->registro['rfc'];
        }

        if(isset($this->registro['nss'])) {
            $registro_emp['nss'] = $this->registro['nss'];
        }

        if(isset($this->registro['celular'])) {
            $registro_emp['telefono'] = $this->registro['celular'];
        }
        $r_emp = (new em_empleado(link: $this->link))->alta_registro(registro: $registro_emp);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_emp);
        }

        $registro_rel_emp['em_empleado_id'] = $r_emp->registro_id;
        $registro_rel_emp['inm_empleado_id'] = $r_alta_bd->registro_id;
        $r_rel_emp = (new inm_rel_emp_emp(link: $this->link))->alta_registro(registro: $registro_rel_emp);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_rel_emp);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($registro['status'])){
            $keys = array('adm_usuario_id', 'inm_horario_id');
            $valida = $this->validacion->valida_ids(keys: $keys, registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
            }

            $keys = array('nombre', 'apellido_paterno');
            $valida = $this->validacion->valida_existencia_keys(keys: $keys, registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
            }

            if (!isset($registro['descripcion'])) {
                $descripcion = $registro['adm_usuario_id'];
                $descripcion .= ' - ' . $registro['inm_horario_id'];
                $descripcion .= ' - ' . $registro['nombre'];
                $descripcion .= ' ' . $registro['apellido_paterno'];
                $registro['descripcion'] = $descripcion;
            }

            if (!isset($registro['razon_social'])) {
                $razon_social = $registro['nombre'];
                $razon_social .= ' ' . $registro['apellido_paterno'];
                if (isset($registro['apellido_materno']) && trim($registro['apellido_materno']) !== '') {
                    $razon_social .= ' ' . $registro['apellido_materno'];
                }
                $registro['razon_social'] = $razon_social;
            }

            if (!isset($registro['descripcion_select'])) {
                $descripcion_select = $registro['razon_social'];
                $registro['descripcion_select'] = $descripcion_select;
            }

            if (!isset($registro['codigo'])) {
                $codigo = $registro['descripcion'];
                $codigo .= ' ' . rand(10000, 99999);
                $registro['codigo'] = $codigo;
            }
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        $r_rel_emp = (new inm_rel_emp_emp(link: $this->link))->filtro_and(filtro:
            array('inm_empleado.id'=>$this->registro_id));
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al maquetar key_selects',data:  $r_rel_emp);
        }

        $registro_emp['nombre'] = $registro['nombre'];
        $registro_emp['ap'] = $registro['apellido_paterno'];
        $registro_emp['am'] = $registro['apellido_materno'];
        $registro_emp['rfc'] = $registro['rfc'];
        $registro_emp['curp'] = $registro['curp'];
        $registro_emp['nss'] = $registro['nss'];
        $registro_emp['im_registro_patronal_id'] = $registro['im_registro_patronal_id'];
        $registro_emp['org_puesto_id'] = $registro['org_puesto_id'];
        $registro_emp['cat_sat_regimen_fiscal_id'] = $registro['cat_sat_regimen_fiscal_id'];
        $registro_emp['cat_sat_tipo_regimen_nom_id'] = $registro['cat_sat_tipo_regimen_nom_id'];
        $registro_emp['cat_sat_tipo_jornada_nom_id'] = $registro['cat_sat_tipo_jornada_nom_id'];
        $registro_emp['fecha_inicio_rel_laboral'] = $registro['fecha_inicio_rel_laboral'];
        $registro_emp['salario_diario'] = $registro['salario_diario'];
        $registro_emp['salario_diario_integrado'] = $registro['salario_diario_integrado'];
        $registro_emp['dp_colonia_postal_id'] = $registro['dp_colonia_postal_id'];
        $registro_emp['calle'] = $registro['calle'];
        $registro_emp['numero_exterior'] = $registro['numero_exterior'];
        $registro_emp['numero_interior'] = $registro['numero_interior'];
        $registro_emp['telefono'] = $registro['celular'];
        if($r_rel_emp->n_registros > 0){
            $r_modifica = (new em_empleado(link: $this->link))->modifica_bd(registro: $registro_emp,
                id: $r_rel_emp->registros[0]['em_empleado_id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al maquetar key_selects',data:  $r_modifica);
            }
        }else{
            $r_emp = (new em_empleado(link: $this->link))->alta_registro(registro: $registro_emp);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_emp);
            }

            $registro_rel_emp['em_empleado_id'] = $r_emp->registro_id;
            $registro_rel_emp['inm_empleado_id'] = $id;
            $r_rel_emp = (new inm_rel_emp_emp(link: $this->link))->alta_registro(registro: $registro_rel_emp);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_rel_emp);
            }
        }

        return $r_modifica_bd;
    }


    public function valida_usuario(string $password, string $usuario){
        if($usuario === ''){
            return $this->error->error(mensaje: 'El usuario no puede ir vacio',data: $usuario);
        }

        if($password === ''){
            return $this->error->error(mensaje: 'El $password no puede ir vacio',data: $password);
        }

        $filtro['adm_usuario.user'] = $usuario;
        $filtro['adm_usuario.password'] = $password;
        $filtro['adm_usuario.status'] = 'activo';

        $r_usuario = $this->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener usuario',data: $r_usuario);
        }

        if((int)$r_usuario->n_registros === 0){
            return $this->error->error(mensaje: 'Error al validar usuario y pass ',data: $usuario);
        }
        if((int)$r_usuario->n_registros > 1){
            return $this->error->error(mensaje: 'Error al validar usuario y pass ',data: $usuario);
        }

        return $r_usuario->registros[0];
    }
}