<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_periodo_asistencia extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_periodo_asistencia';
        $columnas = array($tabla=>false,'inm_horario' => $tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Periodo Asistencia';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $keys = array('inm_horario_id');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys, registro: $this->registro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
        }

        $registro_horario = (new inm_horario(link: $this->link))->registro(
            registro_id: $this->registro['inm_horario_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al validar registro', data: $registro_horario);
        }

        $filtro['inm_horario.id'] = $this->registro['inm_horario_id'];
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['operador'] = '<=';
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['valor'] = 'inm_periodo_asistencia.fecha_fin';
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['comparacion'] = 'AND';
        $filtro_especial[0][(string)$this->registro['fecha_inicio']]['valor_es_campo'] = true;

        $filtro_especial[1][(string)$this->registro['fecha_fin']]['operador'] = '>=';
        $filtro_especial[1][(string)$this->registro['fecha_fin']]['valor'] = 'inm_periodo_asistencia.fecha_inicio';
        $filtro_especial[1][(string)$this->registro['fecha_fin']]['comparacion'] = 'AND';
        $filtro_especial[1][(string)$this->registro['fecha_fin']]['valor_es_campo'] = true;
        $r_filtro_periodo = $this->filtro_and(filtro: $filtro, filtro_especial: $filtro_especial);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
        }

        if ($r_filtro_periodo->n_registros > 0) {
            return $this->error->error(mensaje: 'Error ya existe un periodo del horario ' .
                $registro_horario['inm_horario_descripcion'] .
                ' que entra en el mismo rengo de fechas que se intenta insertar', data: $valida);
        }

        $keys = array('fecha_inicio','fecha_fin');
        $valida = $this->validacion->fechas_in_array(data: $this->registro,keys:  $keys);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $registro_horario['inm_horario_descripcion'];
            $descripcion .= ' - Periodo Inicial: '. $this->registro['fecha_inicio'];
            $descripcion .= ' - Periodo Final: ' .  $this->registro['fecha_fin'];
            $this->registro['descripcion'] = $descripcion;
        }
        
        if (!isset( $this->registro['descripcion_select'])) {
            $descripcion_select = $registro_horario['inm_horario_descripcion'];
            $descripcion_select .= ' - Periodo Inicial: '. $this->registro['fecha_inicio'];
            $descripcion_select .= ' - Periodo Final: ' .  $this->registro['fecha_fin'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if (!isset($this->registro['codigo'])) {
            $codigo = $this->registro['descripcion'];
            $codigo .= ' ' . rand(10000,99999);
            $this->registro['codigo'] = $codigo;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($registro['status'])){
            $keys = array('inm_horario_id');
            $valida = $this->validacion->valida_existencia_keys(keys:  $keys, registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
            }

            $registro_horario = (new inm_horario(link: $this->link))->registro(
                registro_id: $registro['inm_horario_id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al validar registro',data:  $registro_horario);
            }

            $keys = array('fecha_inicio','fecha_fin');
            $valida = $this->validacion->fechas_in_array(data: $registro,keys:  $keys);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
            }

            if (!isset($registro['descripcion'])) {
                $descripcion = $registro_horario['inm_horario_descripcion'];
                $descripcion .= ' - Periodo Inicial: '. $registro['fecha_inicio'];
                $descripcion .= ' - Periodo Final: ' .  $registro['fecha_fin'];
                $registro['descripcion'] = $descripcion;
            }

            if (!isset( $registro['descripcion_select'])) {
                $descripcion_select = $registro_horario['inm_horario_descripcion'];
                $descripcion_select .= ' - Periodo Inicial: '. $registro['fecha_inicio'];
                $descripcion_select .= ' - Periodo Final: ' .  $registro['fecha_fin'];
                $registro['descripcion_select'] = $descripcion_select;
            }

            if (!isset($registro['codigo'])) {
                $codigo = $registro['descripcion'];
                $codigo .= ' ' . rand(10000,99999);
                $registro['codigo'] = $codigo;
            }
        }

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id, reactiva: $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar opinion', data: $r_modifica_bd);
        }

        return $r_modifica_bd;
    }
}