<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_detalle_factura_compra extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_detalle_factura_compra';
        $columnas = array($tabla=>false,'inm_factura_compra'=>$tabla, 'inm_producto'=>$tabla);

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Detalle Factura Compra';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $r_inm_factura_compra = (new inm_factura_compra(link: $this->link))->registro(
            registro_id: $this->registro['inm_factura_compra_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_factura_compra);
        }

        $r_inm_producto = (new inm_producto(link: $this->link))->registro(
            registro_id: $this->registro['inm_producto_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_producto);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $r_inm_factura_compra['gt_proveedor_descripcion'];
            $descripcion .= ' '. $r_inm_producto['inm_producto_descripcion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        if (!isset($this->registro['trasladado'])) {
            $this->registro['trasladado'] = $this->registro['iva'];
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        $filtro_detalle['inm_producto.id'] = $this->registro['inm_producto_id'];
        $r_detalle_factura_compra = $this->filtro_and(filtro: $filtro_detalle);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_detalle_factura_compra);
        }

        if($r_detalle_factura_compra->n_registros > 0){
            $monto_total = 0;
            foreach ($r_detalle_factura_compra->registros as $detalle){
                $monto_total += $detalle['inm_detalle_factura_compra_valor_unitario'];
            }
            $registro_mod['costo_promedio'] = $monto_total / $r_detalle_factura_compra->n_registros;
        }

        $registro_mod['codigo'] = $r_inm_producto['inm_producto_codigo'];
        $registro_mod['descripcion'] = $r_inm_producto['inm_producto_descripcion'];
        $registro_mod['cat_sat_unidad_id'] = $r_inm_producto['cat_sat_unidad_id'];
        $registro_mod['cat_sat_cve_prod_codigo'] = $r_inm_producto['cat_sat_cve_prod_codigo'];
        $registro_mod['cantidad_actual'] = $this->registro['cantidad'] +
            $r_inm_producto['inm_producto_cantidad_actual'];
        $r_modifica = (new inm_producto(link: $this->link))->modifica_bd(registro: $registro_mod,
            id: $this->registro['inm_producto_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_modifica);
        }

        return $r_alta_bd;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        $r_detalle_factura_compra = $this->registro(registro_id: $id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_detalle_factura_compra);
        }

        $filtro_detalle['inm_producto.id'] = $r_detalle_factura_compra['inm_producto_id'];
        $r_detalles_facturas_compra = $this->filtro_and(filtro: $filtro_detalle);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_detalles_facturas_compra);
        }

        if($r_detalles_facturas_compra->n_registros > 0){
            $monto_total = 0;
            foreach ($r_detalles_facturas_compra->registros as $detalle){
                $monto_total += $detalle['inm_detalle_factura_compra_valor_unitario'];
            }

            $registro_mod['costo_promedio'] = $monto_total / $r_detalles_facturas_compra->n_registros;
        }

        $registro_mod['cantidad_actual'] = $r_detalle_factura_compra['inm_producto_cantidad_actual'] -
            $r_detalle_factura_compra['inm_detalle_factura_compra_cantidad'];
        $registro_mod['enviado'] = 'activo';
        $r_modifica = (new inm_producto(link: $this->link))->modifica_bd(registro: $registro_mod,
            id: $r_detalle_factura_compra['inm_producto_id']);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar existencia actual producto', data: $r_modifica);
        }

        $elimina = parent::elimina_bd($id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al eliminar prospecto documento', data: $elimina);
        }

        return $elimina;
    }

}