<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_rel_cheque_comprador extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_cheque_comprador';
        $columnas = array($tabla=>false,'inm_cheque'=>$tabla,'inm_comprador'=>$tabla,'inm_tipo_cheque'=>'inm_cheque',
            'bn_cuenta'=>'inm_cheque');

        $campos_obligatorios = array();

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array();

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion Cheque';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['inm_cheque_id'])) {
            $registro_cheque = array();

            //$registro_cheque['inm_comprador_id'] = $this->registro['inm_comprador_id'];
            $registro_cheque['monto'] = $this->registro['monto'];
            $registro_cheque['nombre_beneficiario'] = $this->registro['nombre_beneficiario'];
            $registro_cheque['inm_tipo_cheque_id'] = $this->registro['inm_tipo_cheque_id'];
            $registro_cheque['bn_cuenta_id'] = $this->registro['bn_cuenta_id'];
            $registro_cheque['numero_cheque'] = '';

            if (isset($this->registro['numero_cheque'])) {
                $registro_cheque['numero_cheque'] = $this->registro['numero_cheque'];
            }

            $r_inm_cheque = (new inm_cheque(link: $this->link))->alta_registro(registro: $registro_cheque);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_inm_cheque);
            }

            $this->registro['inm_cheque_id'] = $r_inm_cheque->registro_id;

            $inm_ubicaciones = (new _inm_comprador())->inm_ubicaciones(
                inm_comprador_id: $this->registro['inm_comprador_id'], link:  $this->link);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al insertar prospecto', data: $inm_ubicaciones);
            }

            $registro = array();
            $registro['inm_ubicacion_id'] = $inm_ubicaciones[0]['inm_ubicacion_id'];
            $registro['monto'] = $this->registro['monto'];
            $registro['fecha'] = date('Y-m-d');
            $registro['referencia'] = $this->registro['nombre_beneficiario'];

            if(trim($this->registro['inm_tipo_cheque_id']) === "1"){
                $registro['inm_concepto_id'] = 19;
            }else if(trim($this->registro['inm_tipo_cheque_id']) === "2"){
                $registro['inm_concepto_id'] = 36;
            }else if(trim($this->registro['inm_tipo_cheque_id']) === "3"){
                $registro['inm_concepto_id'] = 19;
            }

            $r_inm_costo = (new inm_costo(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_inm_costo);
            }

            $registro = array();
            $registro['inm_costo_id'] = $r_inm_costo->registro_id;
            $registro['inm_cheque_id'] = $r_inm_cheque->registro_id;
            $r_rel_costo_cheque = (new inm_rel_costo_cheque(link: $this->link))->alta_registro(registro: $registro);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_rel_costo_cheque);
            }

            unset($this->registro['monto'], $this->registro['nombre_beneficiario'],
                $this->registro['inm_tipo_cheque_id'], $this->registro['numero_cheque']);
        }


        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['inm_comprador_id'];
            $descripcion .= ' ' . $this->registro['inm_cheque_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['inm_comprador_id'];
            $descripcion .= ' ' . $this->registro['inm_cheque_id'] . rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al insertar prospecto', data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

}