<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_llave_control extends _modelo_parent {
    public function __construct(PDO $link)
    {
        $tabla = 'inm_llave_control';
        $columnas = array($tabla => false, 'inm_llave' => $tabla, 'inm_responsable' => $tabla);

        $campos_obligatorios = array('inm_llave_id', 'inm_responsable_id', 'fecha_entrega');

        $columnas_extra = array();
        $renombres = array();

        $atributos_criticos = array('inm_llave_id', 'inm_responsable_id', 'fecha_entrega');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Control de Llaves';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $inm_llave = (new inm_llave(link: $this->link))->registro(
            registro_id: $this->registro['inm_llave_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $inm_llave);
        }

        $inm_responsable = (new inm_responsable(link: $this->link))->registro(
            registro_id: $this->registro['inm_responsable_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $inm_responsable);
        }

        if (!isset($this->registro['descripcion'])) {
            $descripcion = $inm_responsable['inm_responsable_descripcion'];
            $descripcion .= ' ' .  $inm_llave['inm_llave_descripcion'];
            $this->registro['descripcion'] = $descripcion;
        }

        if (!isset($this->registro['codigo'])) {
            $descripcion = $this->registro['descripcion']. rand();
            $this->registro['codigo'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }
}

