<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\inmuebles\controllers;

use base\controller\init;
use config\generales;
use gamboamartin\cat_sat\models\cat_sat_cve_prod;
use gamboamartin\cat_sat\models\cat_sat_unidad;
use gamboamartin\errores\errores;
use gamboamartin\inmuebles\html\inm_factura_compra_html;
use gamboamartin\inmuebles\models\_dropbox;
use gamboamartin\inmuebles\models\inm_detalle_factura_compra;
use gamboamartin\inmuebles\models\inm_doc_factura_compra;
use gamboamartin\inmuebles\models\inm_dropbox_ruta;
use gamboamartin\inmuebles\models\inm_factura_compra;
use gamboamartin\inmuebles\models\inm_producto;
use gamboamartin\system\_ctl_base;
use gamboamartin\system\links_menu;
use gamboamartin\template\html;
use PDO;
use SimpleXMLElement;
use stdClass;
use Throwable;

class controlador_inm_factura_compra extends _ctl_base {
    public string $link_inserta_detalle_bd = '';
    public string $link_inserta_producto_bd = '';
    public string $link_valida_producto_nuevo = '';
    public array $registros_concepto = array();

    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new inm_factura_compra(link: $link);
        $html_ = new inm_factura_compra_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id:  $this->registro_id);

        $datatables = $this->init_datatable();
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable',data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $init_links = $this->init_links();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar links', data: $init_links);
            print_r($error);
            die('Error');
        }
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al inicializar alta',data:  $r_alta, header: $header,ws:  $ws);
        }
        $keys_selects = array();
        $keys_selects = $this->key_select(cols:12, con_registros: true,filtro:  array(), key: 'gt_proveedor_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Proveedor');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }

        $this->row_upd->fecha = date('Y-m-d');

        $fecha = $this->html->input_fecha(cols: 12, row_upd: $this->row_upd, value_vacio: false,
            value: $this->row_upd->fecha);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener input fecha',data:  $fecha, header: $header,ws:  $ws);
        }
        $this->inputs->fecha = $fecha;

        return $r_alta;
    }

    protected function campos_view(): array
    {
        $keys = new stdClass();
        $keys->inputs = array('descripcion','descripcion_producto','cantidad_actual','costo_promedio',
            'cat_sat_cve_prod_codigo');
        $keys->selects = array();

        $init_data = array();
        $init_data['gt_proveedor'] = "gamboamartin\\gastos";
        $init_data['cat_sat_unidad'] = "gamboamartin\\cat_sat";
        $campos_view = $this->campos_view_base(init_data: $init_data,keys:  $keys);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar campo view',data:  $campos_view);
        }


        return $campos_view;
    }



    public function modifica(bool $header, bool $ws = false): array|stdClass
    {

        $r_modifica = $this->init_modifica(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al generar salida de template',data:  $r_modifica,header: $header,ws: $ws);
        }

        $keys_selects = array();
        $keys_selects = $this->key_select(cols:12, con_registros: true,filtro:  array(), key: 'gt_proveedor_id',
            keys_selects: $keys_selects, id_selected: $this->row_upd->gt_proveedor_id, label: 'Proveedor');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $base = $this->base_upd(keys_selects: $keys_selects, params: array(),params_ajustados: array());
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al integrar base',data:  $base, header: $header,ws:  $ws);
        }

        $fecha = $this->html->input_fecha(cols: 12, row_upd: $this->row_upd, value_vacio: false,
            value: $this->row_upd->fecha);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener input fecha',data:  $fecha, header: $header,ws:  $ws);
        }
        $this->inputs->fecha = $fecha;

        return $r_modifica;
    }

    /**
     * Inicializa los elementos mostrables para datatables
     * @return stdClass
     */
    private function init_datatable(): stdClass
    {
        $columns["inm_factura_compra_id"]["titulo"] = "Id";
        $columns["inm_factura_compra_descripcion"]["titulo"] = "Descripcion";

        $filtro = array("inm_factura_compra.id","inm_factura_compra.descripcion");

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }

    protected function init_links(): array|string
    {
        $links = $this->obj_link->genera_links(controler: $this);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar links', data: $links);
            print_r($error);
            exit;
        }

        $link = $this->obj_link->get_link(seccion: "inm_factura_compra", accion: "inserta_producto_bd");
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al recuperar link modifica_direccion', data: $link);
            print_r($error);
            exit;
        }

        $this->link_inserta_producto_bd = $link;

        $link = $this->obj_link->get_link(seccion: "inm_factura_compra", accion: "inserta_detalle_bd");
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al recuperar link modifica_direccion', data: $link);
            print_r($error);
            exit;
        }

        $this->link_inserta_detalle_bd = $link;

        $link = $this->obj_link->get_link(seccion: "inm_factura_compra", accion: "valida_producto_nuevo");
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al recuperar link modifica_direccion', data: $link);
            print_r($error);
            exit;
        }

        $this->link_valida_producto_nuevo = $link;

        return $link;
    }


    public function inserta_producto(bool $header, bool $ws = false): array|stdClass
    {
        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al inicializar alta',data:  $r_alta, header: $header,ws:  $ws);
        }

        $r_factura_compra = (new inm_factura_compra(link: $this->link))->registro(registro_id: $this->registro_id);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al obtener factura compra',data:  $r_factura_compra,
                header: $header,ws:  $ws);
        }

        $keys_selects = array();
        $columns_ds = array('gt_proveedor_razon_social');
        $filtro['gt_proveedor.id'] = $r_factura_compra['gt_proveedor_id'];
        $keys_selects = $this->key_select(cols: 12, con_registros: true, filtro: $filtro, key: 'gt_proveedor_id',
            keys_selects: $keys_selects, id_selected: $r_factura_compra['gt_proveedor_id'], label: 'Proveedor',
            columns_ds: $columns_ds, disabled: true, required: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects,
                header: $header,ws:  $ws);
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }

        $documento_xml_factura = $this->html->input_file(cols: 12,name: 'xml_factura',row_upd:  new stdClass(),value_vacio:  false,
            place_holder: 'XML Factura', required: false);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $documento_xml_factura, header: $header,ws:  $ws);
        }

        $this->inputs->documento_xml_factura = $documento_xml_factura;

        return $inputs;
    }

    /**
     * @throws \Exception
     */
    public function valida_producto_nuevo(bool $header, bool $ws = false):array|stdClass
    {

        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al inicializar alta',data:  $r_alta, header: $header,ws:  $ws);
        }

        $r_factura_compra = (new inm_factura_compra(link: $this->link))->registro(registro_id: $this->registro_id);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al obtener factura compra',data:  $r_factura_compra,
                header: $header,ws:  $ws);
        }

        $keys_selects = array();
        $columns_ds = array('gt_proveedor_razon_social');
        $filtro['gt_proveedor.id'] = $r_factura_compra['gt_proveedor_id'];
        $keys_selects = $this->key_select(cols: 12, con_registros: true, filtro: $filtro, key: 'gt_proveedor_id',
            keys_selects: $keys_selects, id_selected: $r_factura_compra['gt_proveedor_id'], label: 'Proveedor',
            columns_ds: $columns_ds, disabled: true, required: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects,
                header: $header,ws:  $ws);
        }

        $keys_selects = $this->key_select(cols:6, con_registros: true,filtro:  array(), key: 'cat_sat_unidad_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Unidad');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }

        $_FILES['documento'] = $_FILES['xml_factura'];

        $registro_doc['inm_factura_compra_id'] = $this->registro_id;
        $registro_doc['doc_tipo_documento_id'] = '52';

        $r_inm_doc_factura_compra = (new inm_doc_factura_compra(link:$this->link))->alta_registro(registro: $registro_doc);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al convertir en cliente', data: $r_inm_doc_factura_compra,
                    header: $header,ws:  $ws);
        }

        $this->registros_concepto = (new inm_factura_compra(link: $this->link))->obten_registros_xml(
            inm_factura_compra_id: $this->registro_id);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar unidad', data: $this->registros_concepto, header: $header,
                ws: $ws);
        }

        return $this->registros_concepto;
    }

    /**
     * @throws \Exception
     */
    public function obten_productos(bool $header, bool $ws = false){
        $this->registros_concepto = (new inm_factura_compra(link: $this->link))->obten_registros_xml(
            inm_factura_compra_id: $this->registro_id);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar unidad', data: $this->registros_concepto, header: $header,
                ws: $ws);
        }

        if($header){
            $retorno = $_SERVER['HTTP_REFERER'];
            header('Location:'.$retorno);
            exit;
        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($this->registros_concepto, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                return $this->retorno_error(mensaje: 'Error al maquetar estados',data: $e, header: $header, ws: $ws);
            }
            exit;
        }

        return $this->registros_concepto;
    }


    /**
     * @throws \Exception
     */
    /*public function inserta_producto_bd(bool $header, bool $ws = false):array|stdClass
    {
        foreach ($this->registros_concepto as $concepto) {
            $filtro_prod['cat_sat_cve_prod.codigo'] = $concepto['ClaveProdServ'];
            $filtro_prod['inm_producto.descripcion'] = $concepto['Descripcion'];
            $r_producto = (new inm_producto(link: $this->link))->filtro_and(filtro: $filtro_prod);
            if (errores::$error) {
                return $this->retorno_error(mensaje: 'Error al generar producto', data: $r_producto, header: $header,
                    ws: $ws);
            }

            if($r_producto->n_registros > 0){
                $inm_producto_id = $r_producto->registro[0]['inm_producto_id'];
            }else{
                $filtro_unidad['cat_sat_unidad.codigo'] = $concepto['ClaveUnidad'];
                $r_unidad = (new cat_sat_unidad(link: $this->link))->filtro_and(filtro: $filtro_unidad);
                if (errores::$error) {
                    return $this->retorno_error(mensaje: 'Error al generar unidad', data: $r_unidad, header: $header,
                        ws: $ws);
                }

                $inm_unidad_id = -0;
                if($r_unidad->n_registros > 0){
                    $inm_unidad_id = $r_unidad->registros[0]['cat_sat_unidad_descripcion'];
                }
                
                $filtro_cve_prod['cat_sat_cve_prod.codigo'] = $concepto['Clavecve_prod'];
                $r_cve_prod = (new cat_sat_cve_prod(link: $this->link))->filtro_and(filtro: $filtro_cve_prod);
                if (errores::$error) {
                    return $this->retorno_error(mensaje: 'Error al generar cve_prod', data: $r_cve_prod, header: $header,
                        ws: $ws);
                }

                $inm_cve_prod_id = -0;
                if($r_cve_prod->n_registros > 0){
                    $inm_cve_prod_id = $r_cve_prod->registros[0]['cat_sat_cve_prod_descripcion'];
                }

                $registro_prod['inm_unidad_id'] = $inm_unidad_id;
                $registro_prod['cat_sat_cve_prod_id'] = $inm_cve_prod_id;
                $registro_prod['descripcion'] = $concepto['Descripcion'];
                $registro_prod['costo_promedio'] = $concepto['ValorUnitario'];
                $registro_prod['cantidad_actual'] = $concepto['Cantidad'];
                $r_inm_producto = (new inm_producto(link: $this->link))->alta_registro(registro: $registro_prod);
                if (errores::$error) {
                    return $this->retorno_error(mensaje: 'Error al generar link', data: $r_inm_producto,
                        header: $header, ws: $ws);
                }
                $inm_producto_id = $r_inm_producto->registro_id;
            }

            $registro['inm_factura_compra_id'] = $this->registro_id;
            $registro['inm_producto_id'] = $inm_producto_id;
            $registro['cantidad'] = $concepto['Cantidad'];
            $registro['valor_unitario'] = $concepto['ValorUnitario'];
            $registro['subtotal'] = $concepto['Importe'];
            $registro['trasladado'] = $concepto['Trasladado'];
            $registro['retenido'] = $concepto['Retenido'];
            $registro['total'] = $concepto['Total'];
            $r_inm_detalle_factura_compra = (new inm_detalle_factura_compra(link: $this->link))->alta_registro(
                registro: $registro);
            if (errores::$error) {
                return $this->retorno_error(mensaje: 'Error al generar link', data: $r_inm_detalle_factura_compra,
                    header: $header, ws: $ws);
            }
        }

        return $this->registros_concepto;
    }*/

    /**
     * @throws \Exception
     */
    public function inserta_detalle_bd(bool $header, bool $ws = false):array|stdClass
    {
        if(!isset($_POST['asignaciones'])){
            return $this->retorno_error(mensaje: 'Error al obtener registro para alta', data: $_POST,
                header: $header, ws: $ws);
        }

        $r_result = array();
        foreach ($_POST['asignaciones'] as $asignacion) {
            $registro = $asignacion;
            $r_inm_detalle_factura_compra = (new inm_detalle_factura_compra(link: $this->link))->alta_registro(
                registro: $registro);
            if (errores::$error) {
                return $this->retorno_error(mensaje: 'Error al generar link', data: $r_inm_detalle_factura_compra,
                    header: $header, ws: $ws);
            }

            $r_result[] = $r_inm_detalle_factura_compra;
        }

        if($header){
            $retorno = $_SERVER['HTTP_REFERER'];
            header('Location:'.$retorno);
            exit;
        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($r_result, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                return $this->retorno_error(mensaje: 'Error al maquetar estados',data: $e, header: $header, ws: $ws);
            }
            exit;
        }

        return $r_result;
    }

    /**
     * @throws \Exception
     */
    public function inserta_producto_bd(bool $header, bool $ws = false):array|stdClass
    {
        if(!isset($_POST['registro'])){
            return $this->retorno_error(mensaje: 'Error al obtener registro para alta', data: $_POST,
                header: $header, ws: $ws);
        }

        $registro = $_POST['registro'];
        $r_inm_producto = (new inm_producto(link: $this->link))->alta_registro(
            registro: $registro);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al generar link', data: $r_inm_producto,
                header: $header, ws: $ws);
        }

        if($header){
            $retorno = $_SERVER['HTTP_REFERER'];
            header('Location:'.$retorno);
            exit;
        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($r_inm_producto, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                return $this->retorno_error(mensaje: 'Error al maquetar estados',data: $e, header: $header, ws: $ws);
            }
            exit;
        }

        return $r_inm_producto;
    }

    protected function key_selects_txt(array $keys_selects): array
    {
        $keys_selects = (new init())->key_select_txt(cols: 12,key: 'descripcion',
            keys_selects:$keys_selects, place_holder: 'Descripcion');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new init())->key_select_txt(cols: 12,key: 'descripcion_producto',
            keys_selects:$keys_selects, place_holder: 'Descripcion');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new init())->key_select_txt(cols: 6,key: 'costo_promedio',
            keys_selects:$keys_selects, place_holder: 'Costo Promedio');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new init())->key_select_txt(cols: 6,key: 'cantidad_actual',
            keys_selects:$keys_selects, place_holder: 'Cantidad Actual');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new init())->key_select_txt(cols: 6,key: 'cat_sat_cve_prod_codigo',
            keys_selects:$keys_selects, place_holder: 'Clave Producto');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        return $keys_selects;
    }


}
