<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\inmuebles\controllers;

use base\controller\init;
use gamboamartin\errores\errores;
use gamboamartin\inmuebles\html\inm_tipo_credito_html;
use gamboamartin\inmuebles\models\inm_attr_tipo_credito;
use gamboamartin\inmuebles\models\inm_tipo_credito;
use gamboamartin\system\_ctl_base;
use gamboamartin\system\links_menu;
use gamboamartin\template\html;
use PDO;
use stdClass;
use Throwable;

class controlador_inm_tipo_credito extends _ctl_formato {

    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new inm_tipo_credito(link: $link);
        $html_ = new inm_tipo_credito_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id:  $this->registro_id);

        $datatables = $this->init_datatable();
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable',data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al inicializar alta',data:  $r_alta, header: $header,ws:  $ws);
        }
        $keys_selects = array();
        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }

        return $r_alta;
    }

    protected function campos_view(): array
    {
        $keys = new stdClass();
        $keys->inputs = array('descripcion', 'x', 'y');
        $keys->selects = array();

        $init_data = array();
        $campos_view = $this->campos_view_base(init_data: $init_data,keys:  $keys);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar campo view',data:  $campos_view);
        }


        return $campos_view;
    }

    public function get_tipo_credito(bool $header, bool $ws = false){
        $r_tipo_credito = (new inm_tipo_credito(link: $this->link))->registro(registro_id: $_POST['id']);
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al obtener registro de tipo_credito', data: $r_tipo_credito,
                header: $header, ws: $ws);
        }

        if($header){
            $retorno = $_SERVER['HTTP_REFERER'];
            header('Location:'.$retorno);
            exit;
        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($r_tipo_credito, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                return $this->retorno_error(mensaje: 'Error al maquetar estados',data: $e, header: $header, ws: $ws);
            }
            exit;
        }

        return $r_tipo_credito;
    }

    public function get_attr_tipos_credito(bool $header, bool $ws = false){
        $filtro_tipo_credito['inm_tipo_credito.id'] =  $_POST['id'];
        $r_tipo_credito = (new inm_attr_tipo_credito(link: $this->link))->filtro_and(filtro: $filtro_tipo_credito);
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al obtener registro de tipo_credito', data: $r_tipo_credito,
                header: $header, ws: $ws);
        }

        if($header){
            $retorno = $_SERVER['HTTP_REFERER'];
            header('Location:'.$retorno);
            exit;
        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($r_tipo_credito, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                return $this->retorno_error(mensaje: 'Error al maquetar estados',data: $e, header: $header, ws: $ws);
            }
            exit;
        }

        return $r_tipo_credito;
    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {

        $r_modifica = $this->init_modifica(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al generar salida de template',data:  $r_modifica,header: $header,ws: $ws);
        }

        $keys_selects = array();
        $base = $this->base_upd(keys_selects: $keys_selects, params: array(),params_ajustados: array());
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al integrar base',data:  $base, header: $header,ws:  $ws);
        }

        return $r_modifica;
    }

    /**
     * Inicializa los elementos mostrables para datatables
     * @return stdClass
     */
    private function init_datatable(): stdClass
    {
        $columns["inm_tipo_credito_id"]["titulo"] = "Id";
        $columns["inm_tipo_credito_descripcion"]["titulo"] = "Descripcion";
        $columns["inm_tipo_credito_x"]["titulo"] = "X";
        $columns["inm_tipo_credito_y"]["titulo"] = "Y";

        $filtro = array("inm_tipo_credito.id","inm_tipo_credito.descripcion", "inm_tipo_credito.x",
            'inm_tipo_credito.y');

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }


}
