<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\inmuebles\controllers;

use base\controller\init;
use gamboamartin\errores\errores;
use gamboamartin\inmuebles\html\inm_factura_compra_html;
use gamboamartin\inmuebles\models\inm_factura_compra;
use gamboamartin\system\_ctl_base;
use gamboamartin\system\links_menu;
use gamboamartin\template\html;
use PDO;
use SimpleXMLElement;
use stdClass;

class controlador_inm_factura_compra extends _ctl_base {

    public string $link_inserta_producto_bd = '';

    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new inm_factura_compra(link: $link);
        $html_ = new inm_factura_compra_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id:  $this->registro_id);

        $datatables = $this->init_datatable();
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable',data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al inicializar alta',data:  $r_alta, header: $header,ws:  $ws);
        }
        $keys_selects = array();
        $keys_selects = $this->key_select(cols:12, con_registros: true,filtro:  array(), key: 'gt_proveedor_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Proveedor');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }

        $this->row_upd->fecha = date('Y-m-d');

        $fecha = $this->html->input_fecha(cols: 12, row_upd: $this->row_upd, value_vacio: false,
            value: $this->row_upd->fecha);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener input fecha',data:  $fecha, header: $header,ws:  $ws);
        }
        $this->inputs->fecha = $fecha;

        return $r_alta;
    }

    protected function campos_view(): array
    {
        $keys = new stdClass();
        $keys->inputs = array('descripcion');
        $keys->selects = array();

        $init_data = array();
        $init_data['gt_proveedor'] = "gamboamartin\\gastos";
        $campos_view = $this->campos_view_base(init_data: $init_data,keys:  $keys);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar campo view',data:  $campos_view);
        }


        return $campos_view;
    }



    public function modifica(bool $header, bool $ws = false): array|stdClass
    {

        $r_modifica = $this->init_modifica(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al generar salida de template',data:  $r_modifica,header: $header,ws: $ws);
        }

        $keys_selects = array();
        $keys_selects = $this->key_select(cols:12, con_registros: true,filtro:  array(), key: 'gt_proveedor_id',
            keys_selects: $keys_selects, id_selected: $this->row_upd->gt_proveedor_id, label: 'Proveedor');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $base = $this->base_upd(keys_selects: $keys_selects, params: array(),params_ajustados: array());
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al integrar base',data:  $base, header: $header,ws:  $ws);
        }

        $fecha = $this->html->input_fecha(cols: 12, row_upd: $this->row_upd, value_vacio: false,
            value: $this->row_upd->fecha);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener input fecha',data:  $fecha, header: $header,ws:  $ws);
        }
        $this->inputs->fecha = $fecha;

        return $r_modifica;
    }

    /**
     * Inicializa los elementos mostrables para datatables
     * @return stdClass
     */
    private function init_datatable(): stdClass
    {
        $columns["inm_factura_compra_id"]["titulo"] = "Id";
        $columns["inm_factura_compra_descripcion"]["titulo"] = "Descripcion";

        $filtro = array("inm_factura_compra.id","inm_factura_compra.descripcion");

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }

    protected function init_links(): array|string
    {
        $links = $this->obj_link->genera_links(controler: $this);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar links', data: $links);
            print_r($error);
            exit;
        }

        $link = $this->obj_link->get_link(seccion: "inm_factura_compra", accion: "inserta_producto_bd");
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al recuperar link modifica_direccion', data: $link);
            print_r($error);
            exit;
        }
        $this->link_inserta_producto_bd = $link;

        return $link;
    }


    public function inserta_producto(bool $header, bool $ws = false): array|stdClass
    {
        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al inicializar alta',data:  $r_alta, header: $header,ws:  $ws);
        }

        $keys_selects = array();
        $columns_ds = array('gt_proveedor_razon_social');
        $filtro['gt_proveedor.id'] = $this->row_upd->gt_proveedor_id;
        $keys_selects = $this->key_select(cols:12, con_registros: true,filtro:  $filtro, key: 'gt_proveedor_id',
            keys_selects:$keys_selects, id_selected: $this->row_upd->gt_proveedor_id, label: 'Proveedor',
            columns_ds : $columns_ds,required: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects,
                header: $header,ws:  $ws);
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $inputs, header: $header,ws:  $ws);
        }

        $documento_xml_factura = $this->html->input_file(cols: 12,name: 'xml_factura',row_upd:  new stdClass(),value_vacio:  false,
            place_holder: 'XML Factura', required: false);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs',data:  $documento_xml_factura, header: $header,ws:  $ws);
        }

        $this->inputs->documento_xml_factura = $documento_xml_factura;

        return $inputs;
    }


    /**
     * @throws \Exception
     */
    public function inserta_producto_bd(bool $header, bool $ws = false):array|stdClass
    {
        $xmlString = file_get_contents('ruta/a/tu/archivo.xml'); // O coloca tu XML como string directamente

        $xml = new SimpleXMLElement($xmlString);
        $namespaces = $xml->getNamespaces(true);

        if(!isset($namespaces["cfdi"])){
            return $this->retorno_error(
                mensaje: 'Error no existe apartado cfdi en el xml',data:  $namespaces, header: $header,ws:  $ws);
        }

        $conceptosXml = $xml->children($namespaces['cfdi'])->Conceptos->children($namespaces['cfdi'])->Concepto;

        $result = [];

        foreach ($conceptosXml as $concepto) {
            $conceptoData = [
                'ClaveProdServ' => (string)$concepto['ClaveProdServ'],
                'Cantidad' => (string)$concepto['Cantidad'],
                'ClaveUnidad' => (string)$concepto['ClaveUnidad'],
                'Unidad' => (string)$concepto['Unidad'],
                'Descripcion' => (string)$concepto['Descripcion'],
                'ValorUnitario' => (string)$concepto['ValorUnitario'],
                'Importe' => (string)$concepto['Importe'],
                'ObjetoImp' => (string)$concepto['ObjetoImp'],
                'Impuestos' => [
                    'Traslados' => [],
                    'Retenciones' => []
                ]
            ];

            /*if (isset($concepto->Impuestos)) {
                $impuestos = $concepto->Impuestos->children($namespaces['cfdi']);

                // Traslados
                if (isset($impuestos->Traslados)) {
                    foreach ($impuestos->Traslados->children($namespaces['cfdi']) as $traslado) {
                        $conceptoData['Impuestos']['Traslados'][] = [
                            'Base' => (string)$traslado['Base'],
                            'Impuesto' => (string)$traslado['Impuesto'],
                            'TipoFactor' => (string)$traslado['TipoFactor'],
                            'TasaOCuota' => (string)$traslado['TasaOCuota'],
                            'Importe' => (string)$traslado['Importe']
                        ];
                    }
                }

                // Retenciones
                if (isset($impuestos->Retenciones)) {
                    foreach ($impuestos->Retenciones->children($namespaces['cfdi']) as $retencion) {
                        $conceptoData['Impuestos']['Retenciones'][] = [
                            'Base' => (string)$retencion['Base'],
                            'Impuesto' => (string)$retencion['Impuesto'],
                            'TipoFactor' => (string)$retencion['TipoFactor'],
                            'TasaOCuota' => (string)$retencion['TasaOCuota'],
                            'Importe' => (string)$retencion['Importe']
                        ];
                    }
                }
            }*/

            $result[] = $conceptoData;
        }

        return $result;
    }

    protected function key_selects_txt(array $keys_selects): array
    {


        $keys_selects = (new init())->key_select_txt(cols: 12,key: 'descripcion',
            keys_selects:$keys_selects, place_holder: 'Descripcion');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }


        return $keys_selects;
    }


}
