<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\inmuebles\controllers;
use gamboamartin\errores\errores;

class controlador_com_prospecto extends \gamboamartin\comercial\controllers\controlador_com_prospecto {


    public function etapa_bd(bool $header, bool $ws = false): array|\stdClass
    {
        $etapa_bd = parent::etapa_bd(header:false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener template',data:  $etapa_bd);
        }

        $this->retorno_base(registro_id: $_GET['inm_prospecto_id'], result: $etapa_bd, siguiente_view: 'etapa',
            ws: $ws, seccion_retorno: 'inm_prospecto', valida_permiso: true);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener template',data:  $etapa_bd);
        }

        return $etapa_bd;
    }
}
